### ISSUE TITLE
Video generates with subtitles, but no audio

### ISSUE THREAD

**Issue by theoryofevolution** [FujiwaraChoki/MoneyPrinter#10]
Hey,

I'm getting the video generation out, but I'm not able to hear any audio while the audio files are created.

Is there any way to fix this?

**Comment by WaterPheonix196** [comment]
Can you provide the cmd console

**Comment by theoryofevolution** [comment]
This is from point of query entry:

`[+] Cleaned ../temp/ directory
[+] Cleaned ../subtitles/ directory
[Video to be generated]
   Subject: write a video about ai
Artificial Intelligence (AI) has revolutionized the way we live and work. From self-driving cars to virtual assistants, AI is transforming various industries and impacting our daily lives in profound ways. In this video, we will explore the fascinating world of AI and its applications.

**Introduction**
AI, or Artificial Intelligence, is the field of computer science that focuses on creating intelligent machines capable of performing tasks that would typically require human intelligence. These machines can learn, reason, and make decisions based on data and algorithms.

**Applications of AI**
Let's dive into some of the most exciting applications of AI across different industries:

1. **Healthcare**: AI is enhancing medical diagnosis, improving patient care, and even assisting in drug discovery. Machine learning algorithms can analyze medical images to detect diseases like cancer at an early stage, leading to more effective treatment.

2. **Finance**: AI is revolutionizing the finance industry by enabling automated trading, fraud detection, and personalized financial advice. AI-powered chatbots are also being used to provide customer support and answer queries.

3. **Transportation**: Self-driving cars are a prime example of AI in transportation. These vehicles use sensors and AI algorithms to navigate roads, making transportation safer and more efficient. AI is also being used to optimize traffic flow and manage logistics.

4. **Education**: AI is transforming education by personalizing learning experiences for students. Intelligent tutoring systems adapt to individual students' needs, providing tailored content and feedback. AI can also automate administrative tasks, freeing up educators' time.

5. **Retail**: AI is enhancing the retail experience by enabling personalized recommendations based on customer preferences and past behavior. Chatbots are being used to assist customers with their queries, improving customer service.

6. **Manufacturing**: AI is improving efficiency and productivity in manufacturing processes. Robots powered by AI can perform complex tasks with precision and speed, leading to higher production rates and reduced costs.

**Ethical Considerations**
While AI offers numerous benefits, it also raises ethical concerns. Issues such as bias in algorithms, privacy, and job displacement need to be addressed to ensure the responsible development and use of AI.

**Conclusion**
Artificial Intelligence is transforming our world and has the potential to reshape industries and improve our lives in ways we couldn't have imagined. As AI continues to advance, it is crucial to understand its capabilities, limitations, and ethical implications.

This concludes our video on Artificial Intelligence. Thank you for watching!

**End of Script**
["AI video", "Artificial Intelligence video", "AI applications video", "AI in different industries video", "AI impact video"]

Generated 5 search terms: AI video, Artificial Intelligence video, AI applications video, AI in different industries video, AI impact video
	=>
	=>https://player.vimeo.com/external/502524159.hd.mp4?s=5806d59a0c32b8b435e367192a7f4d33bad62aa7&profile_id=175&oauth2_token_id=57447761
	=>
	=>https://player.vimeo.com/external/512209430.sd.mp4?s=917ec11c9a221281add796f5ddf9971eb61bd147&profile_id=139&oauth2_token_id=57447761
	=>
[+] Downloading videos...
[+] Videos downloaded!
[+] Script generated!


	Artificial Intelligence (AI) has revolutionized the way we live and work. From self-driving cars to virtual assistants, AI is transforming various industries and impacting our daily lives in profound ways. In this video, we will explore the fascinating world of AI and its applications.

**Introduction**
AI, or Artificial Intelligence, is the field of computer science that focuses on creating intelligent machines capable of performing tasks that would typically require human intelligence. These machines can learn, reason, and make decisions based on data and algorithms.

**Applications of AI**
Let's dive into some of the most exciting applications of AI across different industries:

1. **Healthcare**: AI is enhancing medical diagnosis, improving patient care, and even assisting in drug discovery. Machine learning algorithms can analyze medical images to detect diseases like cancer at an early stage, leading to more effective treatment.

2. **Finance**: AI is revolutionizing the finance industry by enabling automated trading, fraud detection, and personalized financial advice. AI-powered chatbots are also being used to provide customer support and answer queries.

3. **Transportation**: Self-driving cars are a prime example of AI in transportation. These vehicles use sensors and AI algorithms to navigate roads, making transportation safer and more efficient. AI is also being used to optimize traffic flow and manage logistics.

4. **Education**: AI is transforming education by personalizing learning experiences for students. Intelligent tutoring systems adapt to individual students' needs, providing tailored content and feedback. AI can also automate administrative tasks, freeing up educators' time.

5. **Retail**: AI is enhancing the retail experience by enabling personalized recommendations based on customer preferences and past behavior. Chatbots are being used to assist customers with their queries, improving customer service.

6. **Manufacturing**: AI is improving efficiency and productivity in manufacturing processes. Robots powered by AI can perform complex tasks with precision and speed, leading to higher production rates and reduced costs.

**Ethical Considerations**
While AI offers numerous benefits, it also raises ethical concerns. Issues such as bias in algorithms, privacy, and job displacement need to be addressed to ensure the responsible development and use of AI.

**Conclusion**
Artificial Intelligence is transforming our world and has the potential to reshape industries and improve our lives in ways we couldn't have imagined. As AI continues to advance, it is crucial to understand its capabilities, limitations, and ethical implications.

This concludes our video on Artificial Intelligence. Thank you for watching!

**End of Script** 
Service available!
Audio file saved successfully as '../temp/68222e27-d4c4-4540-9fbe-ad9bfce9d87e.mp3'
Service available!
Audio file saved successfully as '../temp/0b557620-70e7-49f4-8512-c2aba1373fb7.mp3'
Service available!
Audio file saved successfully as '../temp/247fd7e5-4710-4a8b-80bb-459ee4c1646e.mp3'
Service available!
Audio file saved successfully as '../temp/3430aa90-cd32-41fb-bfdb-9a23b585aab6.mp3'
Service available!
Audio file saved successfully as '../temp/348cb10b-14a9-4573-9f94-ae742b11728b.mp3'
Service available!
Audio file saved successfully as '../temp/2a284815-d25c-4f1d-9ca7-096d5288d72b.mp3'
Service available!
Audio file saved successfully as '../temp/f069691b-9b3a-44e3-a9ce-c35189567f3c.mp3'
Service available!
Audio file saved successfully as '../temp/16d211ab-6013-4e0a-863a-6d504f36f7cc.mp3'
Service available!
Audio file saved successfully as '../temp/3d523f0b-817c-41de-b31b-58524598bdf1.mp3'
Service available!
Audio file saved successfully as '../temp/fd7a676c-446b-40f1-a986-298442b9f202.mp3'
Service available!
Audio file saved successfully as '../temp/4a8d494d-3d18-4fe7-bfe4-7d2ca9a4d653.mp3'
Service available!
Audio file saved successfully as '../temp/5410ff4f-7252-4d27-9d1d-436847cb8bee.mp3'
Service available!
Audio file saved successfully as '../temp/043e17a6-fc9e-4d7d-a8dd-2d0009d599e6.mp3'
Service available!
Audio file saved successfully as '../temp/32d730f1-7f45-4956-a6b3-4befba5b111f.mp3'
Service available!
Audio file saved successfully as '../temp/d598c41c-0619-475f-901a-4985d1b638c2.mp3'
Service available!
Audio file saved successfully as '../temp/ecadecf2-f4c7-4ee9-a1d2-d3a24bc3e1db.mp3'
Service available!
Audio file saved successfully as '../temp/74d25ff4-b31a-4a32-b72f-a88c281641ad.mp3'
Service available!
Audio file saved successfully as '../temp/3e3d3bf5-86a2-4039-833d-bb081e7322c2.mp3'
Service available!
Audio file saved successfully as '../temp/677285c4-8769-4f35-9e8e-d96791e3af0f.mp3'
Service available!
Audio file saved successfully as '../temp/aa4877eb-17b4-4e8d-85c1-101acc9b4f41.mp3'
Service available!
Audio file saved successfully as '../temp/4091496e-d2ea-44fe-a170-7fa23e6d68f6.mp3'
MoviePy - Writing audio in ../temp/063af234-6b76-446a-8445-a5737bb34e41.mp3
MoviePy - Done.                                                                 
[+] Subtitles generated.
[+] Combining videos...
[+] Each video will be 100.375 seconds long.
Moviepy - Building video ../temp/dfd8990d-ee05-4bcc-bc3a-671c854a3736.mp4.
Moviepy - Writing video ../temp/dfd8990d-ee05-4bcc-bc3a-671c854a3736.mp4

t:  38%|█████████▉                | 2305/6023 [00:33<00:49, 74.50it/s, now=None]t:  85%|██████████████████████▏   | 5131/6023 [01:37<00:23, 37.55it/s, now=None]Moviepy - Done !                                                                
Moviepy - video ready ../temp/dfd8990d-ee05-4bcc-bc3a-671c854a3736.mp4
Moviepy - Building video ../temp/output.mp4.
MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp3
MoviePy - Done.                                                                 
Moviepy - Writing video ../temp/output.mp4

Moviepy - Done !                                                                
Moviepy - video ready ../temp/output.mp4
[+] Video generated!
[+] Path: output.mp4
127.0.0.1 - - [04/Feb/2024 13:55:21] "POST /api/generate HTTP/1.1" 200 -

`

**Comment by FujiwaraChoki** [comment]
The script is way too long, this is meant for shorts, not long form.

**Comment by PrevosHD** [comment]
> The script is way too long, this is meant for shorts, not long form.

Possible to add a cancel button in frontend if the script is too long so no restart is needed?
