### ISSUE TITLE
[BUG] on git bash installation | No module named srt_equalizer

### ISSUE THREAD

**Issue by vo1d-null** [FujiwaraChoki/MoneyPrinter#102]
**To Reproduce**
1. Go to 'Desktop/{folder}'
2. Click on 'Right click -> Git bash here'
3. Copy-pasted the commands into bash
4. Im getting the error in the screenshot.
![mintty 2024-02-08_23-45-48](https://github.com/FujiwaraChoki/MoneyPrinter/assets/123015737/73d9a1ac-eccb-4c70-8ebb-35bc2bbe8980)

**Desktop (please complete the following information):**
- Windows 10 x64
 - Python Version -3.11.7

**Additional context**
I've tried to pip install srt_equalizer manually but it cannot find it.

**Comment by derekslenk** [comment]
Did you `pip install -r requirements.txt`?  It defines the srt version in there.

It works on WSL2 with python3.11 fwiw

**Comment by vo1d-null** [comment]
Yes.It did bot work
![mintty 2024-02-09_02-09-48](https://github.com/FujiwaraChoki/MoneyPrinter/assets/123015737/265f8ed2-34ec-4e47-8edd-85751a43dfd5)

**Comment by derekslenk** [comment]
You need to execute those one line at a time.
