### ISSUE TITLE
What's TIKTOK_SESSION_ID?

### ISSUE THREAD

**Issue by jcplus** [FujiwaraChoki/MoneyPrinter#104]
Should I become a TikTok developer and grab something from the backend? Thanks in advance.

**Comment by 1NoobDev** [comment]
No need to become developer. It's the session id value of the cookie.

TIKTOK_SESSION_ID: Your TikTok session ID is required. Obtain it by logging into TikTok in your browser and copying the value of the sessionid cookie. 

You can do this using inspector - dev tools (F12).

**Comment by givensuman** [comment]
```javascript
console.log(sessionStorage.getItem("webapp_session_id"))
```
for those that are still lost

**Comment by jcplus** [comment]
Thanks so much
