### ISSUE TITLE
Feature Request: Background Music Option for Enhanced Video Engagement

### ISSUE THREAD

**Issue by timsayshey** [FujiwaraChoki/MoneyPrinter#107]
Before I get into this feature request I just wanted to say thank you for creating and sharing such a cool project! 

**Is your feature request related to a problem? Please describe.**
Yes, the lack of background music in generated videos makes them feel less engaging and dynamic.

**Describe the solution you'd like**
Integrate an option to add background music from a royalty-free library like https://pixabay.com/music/ to the AI video generator tool. Users should be able to select music that fits the mood of their video, just like they can choose the text-to-speech, maybe even provide an input to provide the MP3 url of the pixabay MP3 or other site.

**Describe alternatives you've considered**
Silence, but that does not offer the same level of engagement.

**Additional context**
Adding music can significantly enhance the emotional impact and viewer retention of generated videos.

**Comment by FujiwaraChoki** [comment]
Pushed.
