### ISSUE TITLE
An Error Occured When Clicking Generate [Ubuntu 22]

### ISSUE THREAD

**Issue by hishammir** [FujiwaraChoki/MoneyPrinter#111]
Hi there,
Before opening this i went through the closed issues section and found one more famiIiar issue
 https://github.com/FujiwaraChoki/MoneyPrinter/issues/21   , 
but no solution was there so opening this
 have set this up on Ubuntu VPS running version 22. Whenever i click generate , it shows 
            **"An error occurred. Please try again later."**
            
Below are my screenshot
            
**The error**
             
![Screenshot_1](https://github.com/FujiwaraChoki/MoneyPrinter/assets/30221965/d24e7e55-1c8d-4a06-850c-c541c45cb73c)

**Running Backend**
            
![Screenshot_2](https://github.com/FujiwaraChoki/MoneyPrinter/assets/30221965/2e98ee8c-6403-4569-8b9d-d378ba2c27d7)
             
**Running Frontend**
![Screenshot_3](https://github.com/FujiwaraChoki/MoneyPrinter/assets/30221965/32c019cd-4b53-4611-864f-1a4d6d07562c)

**My .env file**
![Screenshot_4](https://github.com/FujiwaraChoki/MoneyPrinter/assets/30221965/8f4dd3a9-4534-4f43-93ed-e223625fed68)

**Comment by bbrooks870** [comment]
replace localhost with vps ip , in index.html
