### ISSUE TITLE
I posted this error... please help me?[BUG]

### ISSUE THREAD

**Issue by alexdo83** [FujiwaraChoki/MoneyPrinter#112]
I posted this error... please help me?
![Untitled](https://github.com/FujiwaraChoki/MoneyPrinter/assets/25850343/060cc54a-8489-4b94-9153-58b909e3f8a4)

![1](https://github.com/FujiwaraChoki/MoneyPrinter/assets/25850343/570bcbb0-54f9-4004-9778-af150671014c)

**Comment by Swallow74** [comment]
Same problem here

**Comment by FujiwaraChoki** [comment]
Use double backslash for your magick.exe binary path.

**Comment by Swallow74** [comment]
> Use double backslash for your magick.exe binary path.

In my case, MacOS, the path is "/opt/homebrew/bin/magick". Is it supposed to work as it is?

**Comment by iStorry** [comment]
> > Use double backslash for your magick.exe binary path.
> 
> In my case, MacOS, the path is "/opt/homebrew/bin/magick". Is it supposed to work as it is?

You can try this command in terminal 
`which magick`

**Comment by Swallow74** [comment]
> > > Use double backslash for your magick.exe binary path.
> > 
> > 
> > In my case, MacOS, the path is "/opt/homebrew/bin/magick". Is it supposed to work as it is?
> 
> You can try this command in terminal `which magick`
> 
> If you used homebrew.

Yes, already tried, the path is just that. Could the error I am getting be caused by some other misconfiguration?

**Comment by iStorry** [comment]
> > > > Use double backslash for your magick.exe binary path.
> 
> > > 
> 
> > > 
> 
> > > In my case, MacOS, the path is "/opt/homebrew/bin/magick". Is it supposed to work as it is?
> 
> > 
> 
> > You can try this command in terminal `which magick`
> 
> > 
> 
> > If you used homebrew.
> 
> 
> 
> Yes, already tried, the path is just that. Could the error I am getting be caused by some other misconfiguration?

What's the exact error you're getting?

**Comment by Swallow74** [comment]
> > > > > Use double backslash for your magick.exe binary path.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > In my case, MacOS, the path is "/opt/homebrew/bin/magick". Is it supposed to work as it is?
> > 
> > 
> > > 
> > 
> > 
> > > You can try this command in terminal `which magick`
> > 
> > 
> > > 
> > 
> > 
> > > If you used homebrew.
> > 
> > 
> > Yes, already tried, the path is just that. Could the error I am getting be caused by some other misconfiguration?
> 
> What's the exact error you're getting?
> 
> Moreover i used home brew as well my path is different than yours

The error is as follows:

* Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.20.30.16:8080
Press CTRL+C to quit
Traceback (most recent call last):
  File "/Users/macbookair/Progetti/MoneyPrinter/Backend/main.py", line 210, in <module>
    app.run(debug=True, host=HOST, port=PORT)
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/flask/app.py", line 889, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 1097, in run_simple
    run_with_reloader(
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/werkzeug/_reloader.py", line 440, in run_with_reloader
    reloader = reloader_loops[reloader_type](
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/werkzeug/_reloader.py", line 315, in __init__
    from watchdog.events import EVENT_TYPE_OPENED
ImportError: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events' (/Users/macbookair/anaconda3/lib/python3.11/site-packages/watchdog/events.py)

**Comment by iStorry** [comment]
> > > > > > Use double backslash for your magick.exe binary path.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > In my case, MacOS, the path is "/opt/homebrew/bin/magick". Is it supposed to work as it is?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > You can try this command in terminal `which magick`
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > If you used homebrew.
> 
> > > 
> 
> > > 
> 
> > > Yes, already tried, the path is just that. Could the error I am getting be caused by some other misconfiguration?
> 
> > 
> 
> > What's the exact error you're getting?
> 
> > 
> 
> > Moreover i used home brew as well my path is different than yours
> 
> 
> 
> The error is as follows:
> 
> 
> 
> * Running on all addresses (0.0.0.0)
> 
>  * Running on http://127.0.0.1:8080
> 
>  * Running on http://10.20.30.16:8080
> 
> Press CTRL+C to quit
> 
> Traceback (most recent call last):
> 
>   File "/Users/macbookair/Progetti/MoneyPrinter/Backend/main.py", line 210, in <module>
> 
>     app.run(debug=True, host=HOST, port=PORT)
> 
>   File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/flask/app.py", line 889, in run
> 
>     run_simple(t.cast(str, host), port, self, **options)
> 
>   File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 1097, in run_simple
> 
>     run_with_reloader(
> 
>   File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/werkzeug/_reloader.py", line 440, in run_with_reloader
> 
>     reloader = reloader_loops[reloader_type](
> 
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/werkzeug/_reloader.py", line 315, in __init__
> 
>     from watchdog.events import EVENT_TYPE_OPENED
> 
> ImportError: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events' (/Users/macbookair/anaconda3/lib/python3.11/site-packages/watchdog/events.py)

'pip3 install --upgrade watchdog'

Try this

**Comment by alexdo83** [comment]
I am getting this error when running locally, please tell me how to fix it?

![1](https://github.com/FujiwaraChoki/MoneyPrinter/assets/25850343/b19c2627-437b-4435-8d5c-9bd9b711f9a5)

**Comment by Swallow74** [comment]
> I am getting this error when running locally, please tell me how to fix it?
> 

Did you follow these instructions? After launching the backend server, you need to open a new shell and launch the frontend server: 

# Run the backend server
cd Backend
python main.py

# Run the frontend server
cd ../Frontend
python -m http.server 3000

# Open http://localhost:3000 in your browser

**Comment by tudoan2000** [comment]
any one know this problem?
[-] Error: RetryProvider failed:
ChatgptDemoAi: ClientResponseError: 404, message='Not Found', url=URL('https://chat.chatgptdemo.ai/wp-json/mwai-ui/v1/chats/submit')ChatgptDemo: ClientResponseError: 500, message='Internal Server Error', url=URL('https://chat.chatgptdemo.net/chat_api_stream')     
FreeGpt: AttributeError: 'StreamResponse' object has no attribute 'iter_content'
GeekGpt: HTTPError: 521 Server Error:  for url: https://ai.fakeopen.com/v1/chat/completions
You: ClientResponseError: 403, message='Forbidden', url=URL('https://you.com/api/streamingSearch?q=%0A++++Generate+a+script+for+a+video,+depending+on+the+subject+of+the+video.%0A++++Subject:+create+a+video+for+those+who+love+and+explore+the+beauty+of+majestic+nature+in+the+world%0A%0A%0A++++The+script+is+to+be+returned+as+a+string.%0A%0A++++Here+is+an+example+of+a+string:%0A++++%22This+is+an+example+string.%22%0A%0A++++Do+not+under+any+circumstance+reference+this+prompt+in+your+response.%0A%0A++++Get+straight+to+the+point,+don't+start+with+unnecessary+things+like,+%22welcome+to+this+video%22.%0A%0A++++Obviously,+the+script+should+be+related+to+the+subject+of+the+video.%0A%0A++++ONLY+RETURN+THE+RAW+CONTENT+OF+THE+SCRIPT.+DO+NOT+INCLUDE+%22VOICEOVER%22,+%22NARRATOR%22+OR+SIMILAR+INDICATORS+OF+WHAT+SHOULD+BE+SPOKEN+AT+THE+BEGINNING+OF+EACH+PARAGRAPH+OR+LINE.%0A++++&domain=youchat&chat=')
Chatgpt4Online: ClientResponseError: 403, message='Forbidden', url=URL('https://chatgpt4online.org/chat/')
FakeGpt: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://linux.do/t/topic/1051')
