### ISSUE TITLE
Create a python tkinter GUI for the Money Printer

### ISSUE THREAD

**Issue by Bashamega** [FujiwaraChoki/MoneyPrinter#113]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem.
My feature request is to make a tkinter interface for the user, instead of using the web

**Additional context**
I would like  to work on it

**Comment by AndrobaL** [comment]
create a pull request

**Comment by FujiwaraChoki** [comment]
I don't think that's nessecary, in fact it would probably only look worse.

**Comment by Dev2409** [comment]
i can work on it

**Comment by Bashamega** [comment]
> I don't think that's nessecary, in fact it would probably only look worse.

OK
