### ISSUE TITLE
[BUG] Audio not being merged with video

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [FujiwaraChoki/MoneyPrinter#119]
**Describe the bug**
When generating the video, the spoken audio is generated, as well as the video itself with the subtitles, but both aren't combined together at the end.

**To Reproduce**
1. Generate a video
2. wait for it to finish
3. confirm both the full mp3 and full mp4 are there
4. mp4 does _not_ contain the audio

**Expected behavior**
The final video (I suppose not in the temp folder?) should have both the video and the audio in it.

**Desktop (please complete the following information):**
 - OS: Mac 14.1.1 (23B81)
 - Browser Chrome/Firefox
 - Python Version 3.10.8

**Additional context**
The full output looks like this:
```bash
[Video to be generated]
   Subject: Hidden facts about onions, keep it to 1 fact that most people don't know, as well as concise.


**The Hidden Fact About Onions**

Onions contain a compound called quercetin, which has been shown to have anti-inflammatory and antioxidant effects. This compound is most concentrated in the outermost rings of the onion, so peeling off too many layers can lead to a significant loss of this beneficial compound. Therefore, to maximize the health benefits of onions, it's best to use as much of the edible portion as possible, including the outer layers.

Generated 5 search terms: hidden onion facts, onion health benefits, quercetin in onions, maximizing onion health benefits, onion compound quercetin
	=> "hidden onion facts" found 2 Videos
	=> "onion health benefits" found 2 Videos
	=> "quercetin in onions" found 1 Videos
	=> "maximizing onion health benefits" found 2 Videos
	=> "onion compound quercetin" found 2 Videos
[+] Downloading 5 videos...
[+] Videos downloaded!
[+] Script generated!

[+] TikTok TTS Service available!
[+] Audio file saved successfully as '../temp/9045f052-371c-4a61-b08a-1888746e6526.mp3'
[+] TikTok TTS Service available!
[+] Audio file saved successfully as '../temp/b738ab8f-0968-4411-9824-5584ac4bcba3.mp3'
[+] TikTok TTS Service available!
[+] Audio file saved successfully as '../temp/de822145-bf95-48e2-804b-3259a0b7075d.mp3'
MoviePy - Writing audio in ../temp/a7bc9680-6ff2-49c9-810e-1e2fcbe4a8b0.mp3
MoviePy - Done.
[+] Creating subtitles using AssemblyAI
INFO:httpx:HTTP Request: POST https://api.assemblyai.com/v2/upload "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.assemblyai.com/v2/transcript "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://api.assemblyai.com/v2/transcript/ba18dd27-d0e0-48d9-b0be-c964886354b7 "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://api.assemblyai.com/v2/transcript/ba18dd27-d0e0-48d9-b0be-c964886354b7 "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://api.assemblyai.com/v2/transcript/ba18dd27-d0e0-48d9-b0be-c964886354b7/srt "HTTP/1.1 200 OK"
[+] Subtitles generated.
[+] Combining videos...
[+] Each clip will be maximum 7.168000000000001 seconds long.
Moviepy - Building video ../temp/7748c551-7836-4633-a9ea-282d17817afd.mp4.
Moviepy - Writing video ../temp/7748c551-7836-4633-a9ea-282d17817afd.mp4

Moviepy - Done !
Moviepy - video ready ../temp/7748c551-7836-4633-a9ea-282d17817afd.mp4
Moviepy - Building video ../temp/output.mp4.
MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video ../temp/output.mp4

t: 100%|███████████████████████████████████████████████████████████████████▋| 1073/1077 [00:24<00:00, 59.09it/s, now=None]WARNING:py.warnings:/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py:123: UserWarning: Warning: in file ../temp/7748c551-7836-4633-a9ea-282d17817afd.mp4, 6220800 bytes wanted but 0 bytes read,at frame 1076/1077, at time 35.87/35.87 sec. Using the last valid frame instead.
  warnings.warn("Warning: in file %s, "%(self.filename)+

Moviepy - Done !
Moviepy - video ready ../temp/output.mp4
```

**Comment by RicardoMonteiroSimoes** [comment]
Okay, after some more checks it appears that the step `MoviePy - Writing audio in finalTEMP_MPY_wvf_snd.mp3` isn't working as expected, as there is no file like that in `temp`

**Comment by RicardoMonteiroSimoes** [comment]
Okay, it appears that the file is actually named `90aabf47-31e3-4726-be27-c94bac0405c9.mp3`, maybe there is some issue with the naming

**Comment by iStorry** [comment]
> Okay, after some more checks it appears that the step `MoviePy - Writing audio in finalTEMP_MPY_wvf_snd.mp3` isn't working as expected, as there is no file like that in `temp`

> Okay, it appears that the file is actually named 90aabf47-31e3-4726-be27-c94bac0405c9.mp3, maybe there is some issue with the naming

This file `finalTEMP_MPY_wvf_snd.mp3` is generated in the `Backend` directory rather than `temp` i don't why but you can see

**Comment by RicardoMonteiroSimoes** [comment]
Still doesnt exist there, I think it has something to do with an python version incompatibility, as seen in the docker discussion

**Comment by iStorry** [comment]
> Still doesnt exist there, I think it has something to do with an python version incompatibility, as seen in the docker discussion

Once video generation is completed file gets deleted automatically you need to keep an eye while it's merging the video with subtitle and audio.

I was using python3.12 before which was causing issues. python3.11  works fine for me

**Comment by jbrulmans** [comment]
I have the same problem still and I am also on python 3.11. Any other ideas?

**Comment by germansilva45** [comment]
> I have the same problem still and I am also on python 3.11. Any other ideas?

yes, me too. I'm not sure if the python version is the issue here.

**Comment by iStorry** [comment]
Okay finally figured out. It's the codec issue. 
I am guessing you're checking the output video in the Quicktime/iMovie or finder itself if you're using Mac. I don't know about the other OS. 

Can you try with VLC player and you will be able to hear audio

**Comment by jbrulmans** [comment]
@iStorry I have been using VLC also the entire time, still nothing :/

**Comment by germansilva45** [comment]
> Okay finally figured out. It's the codec issue. I am guessing you're checking the output video in the Quicktime/iMovie or finder itself if you're using Mac. I don't know about the other OS.
> 
> Can you try with VLC player and you will be able to hear audio @germansilva45 @jbrulmans

thank you! using VLC worked for me.
