### ISSUE TITLE
ffmpeg stays open

### ISSUE THREAD

**Issue by PrevosHD** [FujiwaraChoki/MoneyPrinter#12]
After finishing one video the next one cannot be generated because a failure while deleting the old files.

```
Moviepy - Done !                                           
Moviepy - video ready ../temp/output.mp4
[+] Video generated!
[+] Path: output.mp4
127.0.0.1 - - [05/Feb/2024 11:08:34] "POST /api/generate HTTP/1.1" 200 -
127.0.0.1 - - [05/Feb/2024 11:09:15] "OPTIONS /api/generate HTTP/1.1" 200 -
[-] Error: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: '../temp/04b5a108-fd17-477a-94b6-f29369f0e67a.mp4'  
```
Currently the only solution for me is stopping the process manually
`taskkill /IM ffmpeg-win64-v4.2.2.exe /F`

Additional:

- Allow pressing the return key instead clicking "Generate"
- Create Cancel Button

Systeminformation:
Windows 11 x64
Python 3.12.1

**Comment by FujiwaraChoki** [comment]
What do you mean by this?

> Allow pressing the return key instead clicking "Generate"

**Comment by PrevosHD** [comment]
On the webpage, frontend.
You have to input a topic and below is a button generate.
If I press return (ENTER) it's not sending like a login or Google search box. I've to click on Generate.

Bei der Eingabe von einem Thema funktioniert es nicht die enter taste zu drücken zum Absenden. Man muss manuell auf Senden, Generate, Klicken.
In Google zb kann man etwas suchen und mit enter es Absenden

English could be hard sometimes.

**Comment by FujiwaraChoki** [comment]
Ahh that's what you mean, sure that can be fixed relatively quickly.

Thanks for bringing this to my attention.

**Comment by FujiwaraChoki** [comment]
Changes have been pushed.
