### ISSUE TITLE
[BUG] no audio in the mp4 

### ISSUE THREAD

**Issue by Aikpo** [FujiwaraChoki/MoneyPrinter#123]
**Describe the bug**
it giving me this error Moviepy - Done !
Moviepy - video ready ../temp/cf753edf-4cfc-40ba-9adb-3b245eed62ee.mp4
[-] Error generating final video: expected str, bytes or os.PathLike object, not NoneType
[-] Client secrets file missing. YouTube upload will be skipped.
[-] Please download the client_secret.json from Google Cloud Platform and store this inside the /Backend directory.
[+] Video generated: None!
ERROR: The process "ffmpeg.exe" not found.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Python Version [3.11]

**Comment by RicardoMonteiroSimoes** [comment]
See here https://github.com/FujiwaraChoki/MoneyPrinter/issues/119

**Comment by shellGhxst** [comment]
Might be valid to check if the ffmpeg.exe is on PATH and put it also on the python´s script folder `...\AppData\Local\Programs\Python\PYTHON_VERSION\Scripts`.

**Comment by FujiwaraChoki** [comment]
Open with VLC.
