### ISSUE TITLE
[BUG] ImageMagick not being detected on Linux

### ISSUE THREAD

**Issue by Eric-Catarina** [FujiwaraChoki/MoneyPrinter#124]
**Describe the bug**
After the MoviePy generating the video, no video is generated and a error appears.

**To Reproduce**
1. Generate video
2. Wait for the video to end

**Expected behavior**
The final video should be generated

**Screenshots**
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/102993694/6b3b97f2-acd5-4689-9195-bc6c755266a4)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Firefox
 - Python Version - Python 3.10.12

**Additional context**
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/102993694/e1053b61-6f3f-4841-9339-630437c8f26c)
Also already tried using the path no the "convert" binary.

**Comment by iStorry** [comment]
> **Describe the bug** After the MoviePy generating the video, no video is generated and a error appears.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Generate video
> 2. Wait for the video to end
> 
> **Expected behavior** The final video should be generated
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/102993694/303690214-6b3b97f2-acd5-4689-9195-bc6c755266a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTQ1MDQsIm5iZiI6MTcwNzQ5NDIwNCwicGF0aCI6Ii8xMDI5OTM2OTQvMzAzNjkwMjE0LTZiM2I5N2YyLWFjZDUtNDY4OS05MTk1LWJjNmM3NTUyNjZhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxNTU2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTNkYWEzOTk3NjRiNTc2MjU0M2VmMTVjZTk3ZjY3M2YwYjcxZGE2Y2RkMTkxMWIyNDcwMzVmMTFkZDVmNzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E--M2dRp49TysW5FP4YZsOD4goKok4jRIz1XrUZaDzw)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Linux Mint
> * Browser Firefox
> * Python Version - Python 3.10.12
> 
> **Additional context** ![image](https://private-user-images.githubusercontent.com/102993694/303691563-e1053b61-6f3f-4841-9339-630437c8f26c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTQ1MDQsIm5iZiI6MTcwNzQ5NDIwNCwicGF0aCI6Ii8xMDI5OTM2OTQvMzAzNjkxNTYzLWUxMDUzYjYxLTZmM2YtNDg0MS05MzM5LTYzMDQzN2M4ZjI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxNTU2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWUwYTYzMjYxZjQwMGY4ZmM2OGQ1OTNkNWIxMmExZWJkYTU3YTQ4OTkzNDViNDQ5M2VjZDEwNjM1ZWUyMmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DNGPkvBVo1Bb7pGcBu-VT_Km0M3h6HxywM03pBE2quU) Also already tried using the path no the "convert" binary.

You need to build the image rather than using the binary file.

```sh
apt-get update && apt-get install -y wget && \
    apt-get install -y build-essential curl libpng-dev && \
    wget https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.0-31.tar.gz && \
    tar xzf 7.1.0-31.tar.gz && \
    rm 7.1.0-31.tar.gz && \
    apt-get clean && \
    apt-get autoremove

sh ./ImageMagick-7.1.0-31/configure --prefix=/usr/local --with-bzlib=yes --with-fontconfig=yes --with-freetype=yes --with-gslib=yes --with-gvc=yes --with-jpeg=yes --with-jp2=yes --with-png=yes --with-tiff=yes --with-xml=yes --with-gs-font-dir=yes && \
    make -j && make install && ldconfig /usr/local/lib/
 ```
 
I hope this will help

**Comment by Eric-Catarina** [comment]
Removing imageMagick and convert, then restalling imageMagick also seems to work.

**Comment by aarjaneiro** [comment]
FYI: you can also run `IMAGEMAGICK_BINARY=/bin/convert python main.py ` (or, if you have IM installed elsewhere, with /bin/convert replaced to that path). `IMAGEMAGICK_BINARY` and other configurables used in moviepy are defined [here](https://github.com/Zulko/moviepy/blob/bc8d1a831d2d1f61abfdf1779e8df95d523947a5/moviepy/config.py#L22) .

**Comment by aarjaneiro** [comment]
By the way, the binary on linux being looked for is typically named [`convert`](https://github.com/Zulko/moviepy/blob/bc8d1a831d2d1f61abfdf1779e8df95d523947a5/moviepy/config.py#L87). It should still be possible to do this without needing to reinstall IM.
