### ISSUE TITLE
[BUG] gpt4 not working

### ISSUE THREAD

**Issue by moshejs** [FujiwaraChoki/MoneyPrinter#128]
**Describe the bug**
Openai version in  requirements.txt needs to be locked, the latest version appears to be incompatible with this project

**To Reproduce**
Select "AI Model" to OpenAI GPT-4

**Expected behavior**
OpenAI GPT-4 generates a script 

**Screenshots**
[Video to be generated]
   Subject: ...
   AI Model: gpt4
[-] Error: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Desktop (please complete the following information):**
 - OS: Mac OS X 14.2.1 (23C71)
 - Python Version 3.11

**Comment by Boanerges1996** [comment]
@FujiwaraChoki you can reassign this to me

**Comment by Boanerges1996** [comment]
@FujiwaraChoki added a  [https://github.com/FujiwaraChoki/MoneyPrinter/pull/134 ](PR)

**Comment by moshejs** [comment]
gpt4 is now working
