### ISSUE TITLE
use pyprojet.toml with poetry package manager

### ISSUE THREAD

**Issue by danilodcn** [FujiwaraChoki/MoneyPrinter#129]
**Is your feature request related to a problem? Please describe.**
It is not a problem. Poetry is a powerful tools to manage this project.

**Describe the solution you'd like**
User this tutorial to install and configure https://python-poetry.org/docs/basic-usage/#initialising-a-pre-existing-project 

**Describe alternatives you've considered**
I can make the changes and put commands in README.dm

**Additional context**
useful links:
- https://python-poetry.org/docs/
- https://python-poetry.org/docs/basic-usage/
- https://python-poetry.org/docs/cli/

**Comment by WaterPheonix196** [comment]
I will try to use this and create a pull request but probably can't for at least a week

**Comment by theharshpat** [comment]
I am working on this issue, almost done with the changes
