### ISSUE TITLE
[BUG] Inaccurate report of video creation

### ISSUE THREAD

**Issue by givensuman** [FujiwaraChoki/MoneyPrinter#136]
**Describe the bug**
The frontend will notify me of a video having been created, whereas the backend logs an error.

**Screenshots**
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/16063606/73d8bffa-0948-4990-a8c0-5436e2e1005e)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Python Version 3.10.12

**Additional context**
Note, this isn't a bug report for the error itself; I'm still setting stuff up and am sure I did something wrong there.

**Comment by iStorry** [comment]
@givensuman make sure your imagemagick path is valid.

**Comment by FujiwaraChoki** [comment]
Make sure you're running from Backend directory
