### ISSUE TITLE
What is TypeError: Failed to fetch?

### ISSUE THREAD

**Issue by jewen1217** [FujiwaraChoki/MoneyPrinter#138]
![error](https://github.com/FujiwaraChoki/MoneyPrinter/assets/59097746/a0b5f905-e7f0-4ac4-b8e1-f35ed5fff11f)

I have no idea on how to solve this issue. Thanks in advance.

**Comment by iStorry** [comment]
@jewen1217 
Please follow instruction carefully

```sh
# Run the backend server
cd Backend
python main.py

# Run the frontend server
cd ../Frontend
python -m http.server 3000
```

**Comment by jewen1217** [comment]
![pic](https://github.com/FujiwaraChoki/MoneyPrinter/assets/59097746/8e8151c0-7a4e-45e5-84e6-de1efa997d9e)
I think it was executed appropriately.

**Comment by gabrielrosendo** [comment]
Are you running it using the Dockerfile?

**Comment by jewen1217** [comment]
> Are you running it using the Dockerfile?

No, I'm not using Dockerfile. I just ran it in Windows 11 terminal.

**Comment by FujiwaraChoki** [comment]
You need to run both at the same time..

**Comment by jewen1217** [comment]
Thanks.
