### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FranklinOP-IND** [FujiwaraChoki/MoneyPrinter#142]
**Describe the bug**

**To Reproduce**
1. Go to 'front page '
2. Click on ' Generate'
4. See error 'An error occurred. Please try again later.'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Python Version [e.g. 3.9]

![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/64591314/0b9af345-7b62-401a-9da9-0ecdcafb97f0)

**Comment by FujiwaraChoki** [comment]
We cannot see the error, please show us the backend log.

**Comment by FranklinOP-IND** [comment]
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/64591314/c6b93b44-6142-42a2-aa4a-baa7be4539fe)

**Comment by FranklinOP-IND** [comment]
> We cannot see the error, please show us the backend log.

[Video to be generated]
   Subject: new video
   AI Model: g4f
INFO:undetected_chromedriver.patcher:patching driver executable C:\Users\Pc\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
[-] Error: RetryProvider failed:
ChatgptDemo: ClientResponseError: 500, message='Internal Server Error', url=URL('https://chat.chatgptdemo.net/chat_api_stream')
ChatgptDemoAi: ClientResponseError: 404, message='Not Found', url=URL('https://chat.chatgptdemo.ai/wp-json/mwai-ui/v1/chats/submit')
Chatgpt4Online: ClientResponseError: 403, message='Forbidden', url=URL('https://chatgpt4online.org/chat/')
FreeGpt: TypeError: AsyncSession.request() got an unexpected keyword argument 'stream'
ChatgptNext: ClientResponseError: 429, message='Too Many Requests', url=URL('https://chat.fstha.com/api/openai/v1/chat/completions')
You: TypeError: AsyncSession.request() got an unexpected keyword argument 'stream'
