### ISSUE TITLE
[BUG]Failed to fetch api's / Syntax error ? &  An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by vo1d-null** [FujiwaraChoki/MoneyPrinter#147]
I run python main.py and IMDisplay opens and stays empty.When i go to the gui i get 404 errors on both the generate and cancel  buttons.When i close the IMDisplay the backend stops with the following message : An attempt was made to access a socket in a way forbidden by its access permissions. I think its because it's trying to fetch the api's on different port? Or i am doing something completly wrong.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser chrome
 - Python Version  3.11

**Screenshots**

![1](https://github.com/FujiwaraChoki/MoneyPrinter/assets/123015737/835f549b-1320-4445-8a28-57026b60005f)
![2](https://github.com/FujiwaraChoki/MoneyPrinter/assets/123015737/a46f9fdd-8bfd-4e62-bc70-e275592b93e6)
![3](https://github.com/FujiwaraChoki/MoneyPrinter/assets/123015737/795438a1-9727-4a09-adcc-62fd3a23baa1)
![5](https://github.com/FujiwaraChoki/MoneyPrinter/assets/123015737/6ce5ad10-9dc1-4684-a0cf-4f15ad353181)
![6](https://github.com/FujiwaraChoki/MoneyPrinter/assets/123015737/09365f5c-4c80-403b-8be3-a2824b080c94)
![7](https://github.com/FujiwaraChoki/MoneyPrinter/assets/123015737/abaf51d3-8688-4148-9e6b-bf8d6d28804d)

**Comment by WaterPheonix196** [comment]
Do you have any blocked ports or firewalls? I had a similar problem with glasswire blocking API requests.

**Comment by vo1d-null** [comment]
No i dont think so.I've used these ports before on a different project,but i dont think that is the problem,bacuse i am opening them one at a time.

**Comment by vo1d-null** [comment]
Update : It seems like there is a problem with the index.html file jasonyfy . Anyway i reinstalled the project now i am stuck at  the second screenshot.I reinstalled ImageMagick and somehow broken the path?I tried to change the path to different different  executables,but no luck sadly.
![5](https://github.com/FujiwaraChoki/MoneyPrinter/assets/123015737/4fa6ba51-b35c-4ca7-9998-93d471290031)
![6](https://github.com/FujiwaraChoki/MoneyPrinter/assets/123015737/2f3a599d-dcc0-4901-b6ae-67045189905e)

**Comment by FujiwaraChoki** [comment]
Please check the other issues, I believe it is mentioned.
