### ISSUE TITLE
[BUG] Error: float division by zero

### ISSUE THREAD

**Issue by N3xi0** [FujiwaraChoki/MoneyPrinter#149]
it does this 
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/145376419/33764afb-3509-4028-9327-b1860dc53d56)

here's my .env settings because i think it can maybe be this
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/145376419/385ba65b-3fc8-4569-90ea-d30ca75a18d8)

**Comment by alien299** [comment]
Same here

**Comment by neker97** [comment]
the file should be only .env not example.env

**Comment by alien299** [comment]
For me its .env only, but got the same issue

**Comment by N3xi0** [comment]
> the file should be only .env not example.env

how can u rename a file in just .env because when i try it just say "blablabla you need a name for the file" because .env is an extension name file not a name

**Comment by FujiwaraChoki** [comment]
Use double backslash

**Comment by N3xi0** [comment]
didnt work

**Comment by toutjavascript** [comment]
Same issue in python console

UI tells "Could not retrieve stock videos: float division by zero"

![Capture d’écran 2024-02-11 à 10 00 28](https://github.com/FujiwaraChoki/MoneyPrinter/assets/30899600/0f2b402b-d81e-454f-8bbd-c96d9f194453)
