### ISSUE TITLE
IMAGEMAGICK_BINARY binary path on MacOS

### ISSUE THREAD

**Issue by tandsong** [FujiwaraChoki/MoneyPrinter#15]
The `README.md` file is missing the path to the ImageMagick binaries, which are used for the `IMAGEMAGICK_BINARY` in .env.

If ImageMagick is installed via Homebrew, the path should be `/opt/homebrew/Cellar/imagemagick/7.1.1-27/bin/magick`

**Comment by FujiwaraChoki** [comment]
It's not missing, it's different for every person. But good point.
