### ISSUE TITLE
[FEATURE] Customizeable script prompt

### ISSUE THREAD

**Issue by radry** [FujiwaraChoki/MoneyPrinter#151]
**Is your feature request related to a problem? Please describe.**
Currently the script prompt is hardcoded and only the subject can influence the outcome. This is fine for a fool proof approach but advanced users shouldn't be locked out of tweaking the prompt easily.

**Describe the solution you'd like**
A by default hidden text box on the Frontend that is populated with the currently hardcoded script prompt. Advanced users can edit/tweak the default prompt there. 

**Describe alternatives you've considered**
Editing gpt.py manually.

**Notes**
It should be easy to implement, just read the content of the input box and have a hardcoded prompt as fallback.

**Comment by phalkmin** [comment]
I was thinking of adding an "advanced" option that adds more context to the prompt directly in the front end, like "tone", "goal", etc. but I don't know how much of it would be accepted on the main branch/repo 🤔
