### ISSUE TITLE
[BUG]  Invalid data found when processing input, songs

### ISSUE THREAD

**Issue by neker97** [FujiwaraChoki/MoneyPrinter#160]
**Describe the bug**
I get the error of Invalid data found when processing input
**To Reproduce**
1) i have uploaded a zip file to filebin
2) inserted the link in the frontend 
3) run
4) after video saved in temp/output.mp4 it gives the error

**Expected behavior**
FInish the run

**Screenshots**

![link](https://github.com/FujiwaraChoki/MoneyPrinter/assets/30214059/d684eda4-a34f-40b7-ace6-0376999adbac)
![Screenshot 2024-02-10 192338](https://github.com/FujiwaraChoki/MoneyPrinter/assets/30214059/7c255f0d-9a68-4a41-8390-281a9bc5aac4)
![Songss](https://github.com/FujiwaraChoki/MoneyPrinter/assets/30214059/ba7a48d3-162c-4e85-a145-f48339099778)

**Additional context**
The zip file contains only a file.mp3

**Comment by FujiwaraChoki** [comment]
Your URL needs to be that of a ZIP-File (ending with ZIP). What you need to do is to copy the link of the download button, not the URL from filebin.
