### ISSUE TITLE
ImageMagick Binary

### ISSUE THREAD

**Issue by qxrmy** [FujiwaraChoki/MoneyPrinter#164]
I don't understand what path to the file should be inserted.  which one did I download or which did I install and take the path to the .exe file?

**Comment by FujiwaraChoki** [comment]
On Windows it's called magick.exe.

**Comment by benjifriedman** [comment]
@FujiwaraChoki and for Mac?

**Comment by sjkelleyjr** [comment]
if you used hombrew

```
/opt/homebrew/Cellar/imagemagick/7.1.1-27/bin/magick
```

**Comment by gijsbotje** [comment]
I believe for Macs with Intel it should be
```
/usr/local/Cellar/imagemagick/7.1.1-27/bin/magick
```

And also change the version number to what you have installed

**Comment by alexandresanlim** [comment]
run `brew info imagemagick` for get path
