### ISSUE TITLE
TikTok Session ID

### ISSUE THREAD

**Issue by benjifriedman** [FujiwaraChoki/MoneyPrinter#165]
I see all the cookies TikTok sets when I log in, but nothing called "session" or session ID. Is it the value from "passport_csrf_token"? "s_v_web_id"? "msToken"? "bm_sv"? Thanks

**Comment by FujiwaraChoki** [comment]
Called `sessionid`.

**Comment by AurganicSubstance** [comment]
i still cant find it; could it be that tiktok hid it because of us!

**Comment by FujiwaraChoki** [comment]
No.
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/78088687/e865936d-b99f-4cce-8696-8e29d31924c5)

**Comment by AurganicSubstance** [comment]
> No. ![image](https://private-user-images.githubusercontent.com/78088687/304390520-e865936d-b99f-4cce-8696-8e29d31924c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjUzNzEsIm5iZiI6MTcwNzgyNTA3MSwicGF0aCI6Ii83ODA4ODY4Ny8zMDQzOTA1MjAtZTg2NTkzNmQtYjk5Zi00Y2NlLTg2OTYtOGUyOWQzMTkyNGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDExNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YjI5ZTI2NzUxMGMwOTUzZjI2OGI3Yjg4YjZkZTM3YmRhYWU5MDY4ZDAzZjBlMDU2YjBmZDI3ODNiOTc3YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lWBEU8lmRgvh4057HDXU8hkWtmMmgHmz8R_2sAuiO8I)

thank you for your reply; i was stupid i thought developer search tool searches through all but it was searching through element only (Chrome), my bad.
