### ISSUE TITLE
error when generating video

### ISSUE THREAD

**Issue by kelanf** [FujiwaraChoki/MoneyPrinter#169]
When generating a video I get this error and cant find a fix

Could not retrieve stock videos: HTTPSConnectionPool(host='weilbyte.github.io', port=443): Max retries exceeded with url: /tiktok-tts/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))

**Comment by EngineerToby** [comment]
Just from looking at what you provided looks like an issue with retrieving stock videos due to an SSL error. I would check the SSL certificate or maybe an outdated SSL library issue.
