### ISSUE TITLE
[-] Error: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ArisenGHG** [FujiwaraChoki/MoneyPrinter#17]
Getting this error after the programm is trying to create the video. 
Dont know how to fix this :(

**Comment by burhankhair** [comment]
Are you still facing the issue?

**Comment by ArisenGHG** [comment]
yes

**Comment by franmartin-xyz** [comment]
yeah I have the same issue in win 10, also what ImageMagick Display are you using?

**Comment by ArisenGHG** [comment]
> yeah I have the same issue in win 10, also what ImageMagick Display are you using?

The newest one for win 11 7.1.1-27

**Comment by franmartin-xyz** [comment]
I think the error [-] Error: expected str, bytes or os.PathLike object, not NoneType is because of the path to the  ImageMagick Display make sure you copied it correctly

**Comment by FujiwaraChoki** [comment]
> I think the error [-] Error: expected str, bytes or os.PathLike object, not NoneType is because of the path to the ImageMagick Display make sure you copied it correctly

Correct. Also, this is not a bug report. Please open a blank issue next time or simply ask in the discord.

**Comment by ArisenGHG** [comment]
now it works .-. my dumb ass forgot to remove the "" sign it was ""path"". Thats why it didn't work.

**Comment by ArisenGHG** [comment]
> > I think the error [-] Error: expected str, bytes or os.PathLike object, not NoneType is because of the path to the ImageMagick Display make sure you copied it correctly
> 
> Correct. Also, this is not a bug report. Please open a blank issue next time or simply ask in the discord.

Okay ^^
