### ISSUE TITLE
Text position

### ISSUE THREAD

**Issue by dheluxe** [FujiwaraChoki/MoneyPrinter#172]
Please add a text positioning option. Not only in the middle, but we can also customize their position.

**Comment by jankapunkt** [comment]
I would also add, that font family and color should be configurable, too, so in order to maximize profit :money_mouth_face:

**Comment by FujiwaraChoki** [comment]
> I would also add, that font family and color should be configurable, too, so in order to maximize profit 🤑

Please open a seperate `Feature` issue.

**Comment by FujiwaraChoki** [comment]
This has been added. Thank you for the request.

**Comment by dheluxe** [comment]
Thank you so much. love it. 😍
