### ISSUE TITLE
ERROR: The process "ffmpeg.exe" not found.

### ISSUE THREAD

**Issue by franmartin-xyz** [FujiwaraChoki/MoneyPrinter#18]
when I run the app ffmpeg.exe is not found

**Expected behavior**
Should be able to use ffmpeg.exe

**Screenshots**
this is the error
![error](https://github.com/FujiwaraChoki/MoneyPrinter/assets/76660514/5781e241-a638-4208-a34f-9dc3e49d53e6)
ffmpeg.exe is installed and the path is applied globally
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/76660514/0756f0aa-e6f0-4606-9bc3-13f90f18648b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Python Version 3.9

**Comment by FujiwaraChoki** [comment]
Don't worry - this is merely to stop all running processes at the end, so another video can be generated, without restarting the server. This is completely normal and not a problem.

**Comment by franmartin-xyz** [comment]
I didnt get it apologies

**Comment by FujiwaraChoki** [comment]
> This is completely normal and not a problem.
