### ISSUE TITLE
[BUG] Trying to use songs, MoviePy throws error `file /temp/None could not be found!` 

### ISSUE THREAD

**Issue by kerta1n** [FujiwaraChoki/MoneyPrinter#184]
When using either a mp3 file placed in the Songs/ directory OR using a direct Filebin link, MoviePy will throw the error that /temp/None could not be found. I'd assume this stems from line 15 of Backend/utils.py

![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/36344851/ccc2381a-8dcf-441a-9940-6ad567147d7b)

`INFO:utils:Chose_ song: Undertale OST - Fallen Down [Reprise] (Slowed).mp3
[-] Error: MoviePy error: the file ../temp/None could not be found!
Please check that you entered the correct path.`

**Comment by neker97** [comment]
can i see the complete zip url you used? because i have 2 suspect
1)you put directly a mp3 files instead of a zip file which contain the mp3 file
2)spaces can be annoying, so use underscore instead of spaces

**Comment by kerta1n** [comment]
Yep, I think I'll retry w/o underscores
https://filebin.net/ql6ucpjtejb71q0d/Undertale_OST_-_Fallen_Down__Reprise___Slowed_.zip

**Comment by kerta1n** [comment]
Error still persists even using dashes

`INFO:utils:Chose song: UndertaleOST-FallenDown-slowed.mp3
[-] Error: MoviePy error: the file ../temp/None could not be found!
Please check that you entered the correct path.`

**Comment by FujiwaraChoki** [comment]
Are you running main.py from
backend directory?

**Comment by kerta1n** [comment]
Yep, whenever I start MP (from ./moneyprinter/) I do
`cd Backend
screen -L python3 main.py
cd ../Frontend
screen -L python3 -m http.server 3000`

**Comment by FujiwaraChoki** [comment]
It may be because of the file name, not sure what else could be causing this issue.

**Comment by Johan-Kok** [comment]
I had a similar problem stemming from movie.py - the movie.py  configuration did  not automatically pickup my configuration, and made the ImageMagick location zero instead of providing it's the executable - Maybe good to have a look at those.

**Comment by kerta1n** [comment]
> I had a similar problem stemming from movie.py - the movie.py  configuration did  not automatically pickup my configuration, and made the ImageMagick location zero instead of providing it's the executable - Maybe good to have a look at those. 
It runs now even with ticking the 'use music' box, but no music is applied. I have to manually upload to clip champ and overlay from there
