### ISSUE TITLE
[BUG] Custom prompt field error

### ISSUE THREAD

**Issue by kerta1n** [FujiwaraChoki/MoneyPrinter#189]
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/36344851/7d6df650-e1bb-4142-a883-b172db45d3c5)

Caused by #179

**Comment by neker97** [comment]
Easy to fix. the problem is the cache because it's a FrontEnd feature,so
1) open the app
2) click inspect element or F12
3) turn back to the app
4) keep pressed on the refresh button
5) click "refresh and clean the cache" (or something like this)

else you have to clean the cache manually

**Comment by kerta1n** [comment]
Clearing cookies, starting fresh, nor did reinstalling all py deps work
