### ISSUE TITLE
[-] Error: Could not find a backend to open `C:\Users\user\AppData\Local\Temp\tmp5ueaib09.png`` with iomode `ri`

### ISSUE THREAD

**Issue by LiveQCC** [FujiwaraChoki/MoneyPrinter#19]
Title shows the error message that is returned from the backend. It also gave a error that "Transperent" directory was not found in the back end?

**Comment by FujiwaraChoki** [comment]
Please be more descriptive, could you also provide some screenshots?

**Comment by LiveQCC** [comment]
> Please be more descriptive, could you also provide some screenshots?

Sorry did not reply instead commented. Still new to this. But ive provided screenshots of what i know in the comment.

**Comment by FujiwaraChoki** [comment]
`pip install imageio[pyav] imageio[opencv]`

Also, what is your Env file named, and what are the contents? (Censor the API Keys)

**Comment by StreamLightt** [comment]
Hello, for me the error was raised at this point : 
main.py : 
`final_video_path = generate_video(combined_video_path, tts_path, subtitles_path, n_threads or 2, subtitles_position, text_color or "#FFFF00")`

This was calling `generate_video` in the `video.py` file.
In the `generate_video` function the error was in this line : `subtitles = SubtitlesClip(subtitles_path, generator)`
At this step it was calling ImageMagick and I think this interaction generated the error.

In my case in the .env file I had put the .exe file that I downloaded from the website it was someting like that : 
`IMAGEMAGICK_BINARY="C:\Users\Toufik\Desktop\MoneyPrinter\ImageMagick-7.1.1-38-Q16-HDRI-x64-dll.exe"

I change it for the path of the .exe file that is generated after the installation of ImageMagick 
Now in my .env I have something like that : 
IMAGEMAGICK_BINARY="C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe"

This fixed the issue for me. If it can help anyone :)
`
