### ISSUE TITLE
[BUG] No errors displayed in Backend logs, but I get "Please try again later"

### ISSUE THREAD

**Issue by kerta1n** [FujiwaraChoki/MoneyPrinter#191]
No indication as to what's wrong now

![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/36344851/389d347d-77a1-4bbb-b97a-1f14e981c901)

` * Running on http://69.87.0.166:8080`
`INFO:werkzeug:Press CTRL+C to quit`
`INFO:werkzeug: * Restarting with stat`
`WARNING:playsound:playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.`
`WARNING:werkzeug: * Debugger is active!`
`INFO:werkzeug: * Debugger PIN: 373-733-206`

**Comment by kerta1n** [comment]
This was just cloned btw

**Comment by FujiwaraChoki** [comment]
Go to `localhost:3000`, not your IP

**Comment by kerta1n** [comment]
.166 is the server IP, already tried changing on app.js, but issue persists

**Comment by kerta1n** [comment]
Fixed by not relaunching screen after editing app.js localhost entries
