### ISSUE TITLE
[Feature] Multiples choices of backgrounds (YouTube Video, Pexel...)

### ISSUE THREAD

**Issue by YotomiY** [FujiwaraChoki/MoneyPrinter#196]
Hello,
During the last week I have being testing the project and I think is pretty cool. But there is only one thing in my opinion that's missing: the possibility to choose a background. In the Frontend, you can choose between 3 option: 
```
1. Local video
2. YouTube video (asking the link to download)
3. Pexel (already existing Feature)
```

**Additional context**
I think this can be great because you can choose manually the background video from a YouTube video
(I also want to know if the YouTube part could be detailed a little because it is not very clear where the client_secret.json is obtained from.)
Thx
@YotomiY

**Comment by FujiwaraChoki** [comment]
If someone makes a PR, I'll gladly merge it!

**Comment by kerta1n** [comment]
Starting point would be https://github.com/elebumm/RedditVideoMakerBot
