### ISSUE TITLE
Error: 'videos'

### ISSUE THREAD

**Issue by Hades1081** [FujiwaraChoki/MoneyPrinter#2]
[-] Error: 'videos'
127.0.0.1 - - [01/Feb/2024 11:49:43] "POST /api/generate HTTP/1.1" 200 -

the directory may be missing

**Comment by Hades1081** [comment]
Python-dotenv could not parse statement starting at line 4
 * Serving Flask app 'main'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.178.30:8080
Press CTRL+C to quit
 * Restarting with stat
Python-dotenv could not parse statement starting at line 4
 * Debugger is active!
 * Debugger PIN:

127.0.0.1 - - [01/Feb/2024 12:20:39] "POST /api/generate HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2024 12:20:55] "OPTIONS /api/generate HTTP/1.1" 200 -
[+] Cleaned ./temp/ directory
[+] Cleaned ./subtitles/ directory
[Video to be generated]
   Subject: pizza
**Pizza Video Script**

Today, we're diving into the world of pizza. From its origins in Italy to its status as a beloved global dish, pizza has captured the hearts and taste buds of people everywhere. Let's explore the art of making the perfect pizza, from the dough to the toppings, and uncover the secrets behind this iconic culinary delight. Whether you're a fan of classic margherita or adventurous with your toppings, there's a pizza for everyone. Join us on this delicious journey as we celebrate the magic of pizza!
["pizza video", "pizza making", "pizza toppings", "perfect pizza", "pizza journey"]

Generated 5 search terms: pizza video, pizza making, pizza toppings, perfect pizza, pizza journey
[-] Error: 'videos'
127.0.0.1 - - [01/Feb/2024 12:21:12] "POST /api/generate HTTP/1.1" 200 -

IMAGEMAGICK_BINARY="C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\" # Download from https://imagemagick.org/script/download.php

**Comment by FujiwaraChoki** [comment]
Do you have python-dotenv installed? Also, your .env file should be located in the root directory of the project.

**Comment by FujiwaraChoki** [comment]
Also, imagemagick binary is the location to magick.exe.

**Comment by Hades1081** [comment]
> dotenv
Requirement already satisfied: python-dotenv in c:\users\seo\appdata\roaming\python\python311\site-packages (1.0
yes .env is in the root

imagemagick binary is the location
C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\ or C:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\

**Comment by FujiwaraChoki** [comment]
`C:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\magick.exe` is the path

**Comment by FujiwaraChoki** [comment]
Also, could you please execute `tree` command so I can see your folder structure...

**Comment by Hades1081** [comment]
C:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\magick.exe is the path 

That was the problem
