### ISSUE TITLE
Make font family / font weight / font colour configurable

### ISSUE THREAD

**Issue by jankapunkt** [FujiwaraChoki/MoneyPrinter#200]
**Is your feature request related to a problem? Please describe.**
Currently the font is displayed using a serif font in yellow color

**Describe the solution you'd like**
Allow the option to choose a custom font, may it be a local one or a webfont.

**Describe alternatives you've considered**
Consider the font config in prompts?

**Additional context**
Related: #172

**Comment by fraro** [comment]
That would be really helpful, as the default font does not handle language specific chars (like german "Umlaut").

**Comment by FujiwaraChoki** [comment]
Well you can already do that... It says how to change the font in the README

**Comment by FujiwaraChoki** [comment]
No response
