### ISSUE TITLE
[-] Error generating final video: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Batti0** [FujiwaraChoki/MoneyPrinter#204]
[-] Error generating final video: expected str, bytes or os.PathLike object, not NoneType

**Comment by Ashes47** [comment]
This seems like a dublicate issue, can you close this @Batti0

**Comment by Batti0** [comment]
pleas help me. I am working on kali linux and I dont know how to solve this proplem Ashes47
