### ISSUE TITLE
ability to add gameplay footage to the bottom of the video

### ISSUE THREAD

**Issue by oopsitsdeleted** [FujiwaraChoki/MoneyPrinter#206]
**Is your feature request related to a problem? Please describe.**
ability to put gameplay footage (minecraft, subway surfers, gta5 racing)

**Describe the solution you'd like**
have a check mark and put gameplay footage if enabled

**Describe alternatives you've considered**
idk

**Additional context**
i love ai brainrot

**Comment by FujiwaraChoki** [comment]
No. ❗️
