### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by takuruk1** [FujiwaraChoki/MoneyPrinter#209]
**Describe the bug**
Main.py exits out with the code : ModuleNotFoundError: No module named 'g4f'

**To Reproduce**
1. CD into Backend
2. Run Python main.py

**Expected behavior**
The script would run normally

**Desktop**
 - OS: Windows
 - Python Version 3.12.2

**Additional context**
Full logs;

C:\Users\user\Documents\YTShorts\MoneyPrinter\Backend>python main.py
Traceback (most recent call last):
  File "C:\Users\user\Documents\YTShorts\MoneyPrinter\Backend\main.py", line 3, in <module>
    from gpt import *
  File "C:\Users\user\Documents\YTShorts\MoneyPrinter\Backend\gpt.py", line 3, in <module>
    import g4f
ModuleNotFoundError: No module named 'g4f'

**Comment by djsv23** [comment]
I'm not sure if you did this because it isn't mentioned in your steps to reproduce, but you need to install the required packages, it's the 2nd step in the Readme after cloning the repository: 

# Install requirements
pip install -r requirements.txt

**Comment by bartex100** [comment]
did you ran "pip install -r requirements.txt"?

**Comment by takuruk1** [comment]
I ran the commands provided in the README.md, yes. Even `pip install -r requirements.txt`

**Comment by kerta1n** [comment]
`pip3.12 install -U g4f`

**Comment by FujiwaraChoki** [comment]
Run it as a module; `python -m pip install g4f`.
