### ISSUE TITLE
Error occurs when clicking the button "generate"

### ISSUE THREAD

**Issue by Grungoos** [FujiwaraChoki/MoneyPrinter#21]
**Describe the bug**
Does not generate a youtube short

**To Reproduce**
pip install --upgrade setuptools
pip install --user -r requirements.txt
cp .env.example .env
cd Backend
python main.py
cd ../Frontend
python -m http.server 3000
http://localhost:3000

**Screenshots**
![grafik](https://github.com/FujiwaraChoki/MoneyPrinter/assets/57602696/743cd587-83a8-4263-90b4-ac4e9b3aff2b)

**Desktop**
 - OS: [Windows]
 - Browser [Firefox]
 - Python Version [3.9]

**Comment by FujiwaraChoki** [comment]
Did you fill out the environment variables in the `.env` file?

**Comment by FujiwaraChoki** [comment]
Also, show me the output from your backend.
