### ISSUE TITLE
[BUG] An error occurred during TTS: Incorrect padding

### ISSUE THREAD

**Issue by Syycorax** [FujiwaraChoki/MoneyPrinter#211]
**Describe the bug**
[-] An error occurred during TTS: Incorrect padding
It Mooviepy then fails to find the mp3 file

**Comment by FujiwaraChoki** [comment]
Poorly explained, very bad issue.

**Comment by Syycorax** [comment]
Sorry I was on a hurry and had to power my computer off., I wanted to keep the log, so I could add more details later.
This happened during the TTS step. No audio got generated, the script just outputted the line above. I wasn't able to reproduce on later runs

Happened on Linux, cloned this afternoon on Python 3.11.7.

Let me know if you have any more details I could share that would help you

**Comment by FujiwaraChoki** [comment]
That's fine - maybe try asking in the discord (pretty sure someone had this issue already)
