### ISSUE TITLE
I have done the complete setup but it is not running

### ISSUE THREAD

**Issue by deepsvks123** [FujiwaraChoki/MoneyPrinter#213]
![Screenshot 2024-02-12 231217](https://github.com/FujiwaraChoki/MoneyPrinter/assets/156742655/6b99b259-82d4-41e1-b075-c483bb5a672d)

**Comment by neker97** [comment]
show the backend log

**Comment by deepsvks123** [comment]
![Screenshot 2024-02-13 102023](https://github.com/FujiwaraChoki/MoneyPrinter/assets/156742655/ce8d82ec-3dfb-4204-9a2e-aff234c0f86b)

sir please help

**Comment by deepsvks123** [comment]
![Screenshot 2024-02-13 222025](https://github.com/FujiwaraChoki/MoneyPrinter/assets/156742655/d6b2780d-37ec-4ca0-b087-e6939482257a)
please error solved  No module named 'g4f'

**Comment by deepsvks123** [comment]
![Screenshot 2024-02-13 230244](https://github.com/FujiwaraChoki/MoneyPrinter/assets/156742655/cdcda809-5f59-4a83-9538-bed7a68acddb)
 Sir please check this

**Comment by amacsmith** [comment]
@FujiwaraChoki Ya same here and there is no backend log being generated. I do however have all preflights failing. So maybe it is a cors issue.

**Comment by deepsvks123** [comment]
Sir this error resolve and, Sir when I type text and generate it, video and voice are coming separately and not merged, so how to merge..

**Comment by FujiwaraChoki** [comment]
This is the tenth time someone opens this issue; visit `localhost:3000`, not `127.0.0.1:3000`
