### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Drabs171** [FujiwaraChoki/MoneyPrinter#217]
**Describe the bug**
When running pip install requirements.txt in a new environment, I run into an issue with playsound, i tried installing it specifically running pip install git+https://github.com/[username]/playsound.git
 didnt work, and its saying that its not compatible with 3.11

**To Reproduce**
1. Go to the Directory
2. Type pip install playsound
3. See error

**Expected behavior**
Thought the installion process would run smoothly

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [ edge]
 - Python Version [ 3.11]

**Comment by FujiwaraChoki** [comment]
See FAQ Section.
