### ISSUE TITLE
[BUG] Youtube upload not working, UI stuck despite video and metadata getting generated

### ISSUE THREAD

**Issue by sree-kanth** [FujiwaraChoki/MoneyPrinter#219]
The video and youtube metadata get generated, but the UI is stuck and doesn't upload the video to Youtube. I had to hit "Cancel" on the UI after waiting for a long time.

<img width="1436" alt="Screenshot 2024-02-13 at 10 12 08 AM" src="https://github.com/FujiwaraChoki/MoneyPrinter/assets/8230457/e46449c3-b442-42ec-b9b5-48edc6780fcc">

**Comment by FujiwaraChoki** [comment]
Generating the metadata takes long, it's not really stuck
