### ISSUE TITLE
Error generate "Could not retrieve stock videos: float division by zero"

### ISSUE THREAD

**Issue by vidvansh** [FujiwaraChoki/MoneyPrinter#22]
**Describe the bug**
Video is not generating and a pop up is appearing on the browser and then the process terminates

**To Reproduce**
1. Tun the program as normal
2. Input string in the browser
3. Error appears

**Expected behavior**
Audio is generated but a pop up appears on the browser "Could not retrieve stock videos: float division by zero"

**Screenshots**
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/56179464/4fb7bad9-04f6-40c8-ba69-7470d3714689)
**Desktop (please complete the following information):**
 - win 10 
 - Edge browser
 - Python Version 3.10

**Additional context**
This is another thing i see in the console.
I am not sure which is causing the issue but both the error seems related
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/56179464/464c1e3f-927e-4a6b-8a75-dbb10bfa4307)

**Comment by GregHilston** [comment]
@vidvansh Did you make any progress on this, as I'm running into the same issue? I know that @FujiwaraChoki has no plans to fix it, but figured I'd ask, to help myself and others ;)
