### ISSUE TITLE
[BUG]   How to set the IMAGEMAGICK_BINARY path on a Macbook?

### ISSUE THREAD

**Issue by hulonghua-devin** [FujiwaraChoki/MoneyPrinter#228]
I downloaded ImageMagick to a local directory and set the IMAGEMAGICK_BINARY path as "/Users/hulonghua/code/open_source/MoneyPrinter/ImageMagick/ImageMagick-7.0.10/bin/magick", but an error occurred. How should I set the path? The error is as follows:

<img width="365" alt="image" src="https://github.com/FujiwaraChoki/MoneyPrinter/assets/127592578/97c16571-f599-474d-8813-117cecf8a669">

<img width="1171" alt="image" src="https://github.com/FujiwaraChoki/MoneyPrinter/assets/127592578/e8194498-b19a-435f-939a-b5c89e413263">

**Comment by FujiwaraChoki** [comment]
Please check the other issues :(

**Comment by UltraInstinct0x** [comment]
Anyone trying to fix this, just 
`IMAGEMAGICK_BINARY="/usr/bin/convert" `
use this if you are on docker.

If its docker, its just convert. If its running on **_your_** mac, then use a path like that. Or just use below after installing it with homebrew (Silicone only)
`/opt/homebrew/Cellar/imagemagick/7.1.1-38/bin/magick`
And for Intel:
`/usr/local/Cellar/imagemagick/`
