### ISSUE TITLE
[BUG] Termcolor missing

### ISSUE THREAD

**Issue by Miner16** [FujiwaraChoki/MoneyPrinter#229]
**Describe the bug**
This error returns with running the backend main.py
```
Traceback (most recent call last):
  File "C:\Users\Kasutaja\OneDrive\Työpöytä\MoneyPrinter\Backend\main.py", line 2, in <module>
    from utils import *
  File "C:\Users\Kasutaja\OneDrive\Työpöytä\MoneyPrinter\Backend\utils.py", line 9, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version 3.11
**Additional context**
Tried running pip install termcolor, didn't help

**Comment by Miner16** [comment]
You marked this as not planned, but could you at least tell me how to fix it or give me a lead?

**Comment by FujiwaraChoki** [comment]
Make sure to use the right interpreter
