### ISSUE TITLE
[BUG] do not use localhost as endpoint but a variable

### ISSUE THREAD

**Issue by grigio** [FujiwaraChoki/MoneyPrinter#233]
**Describe the bug**
if you use MP in lan `localhost` do not work, so you should be able to specify the backend hostname

**To Reproduce**

https://github.com/FujiwaraChoki/MoneyPrinter/blob/de59064d0f60a9f43cc787bf6b38ff7e1358ae10/Frontend/app.js#L76

**Comment by FujiwaraChoki** [comment]
1. This is not a bug, but a feature request.
2. This is so easy to change that there really is no need for this.

**Comment by grigio** [comment]
i know but it would be cleaner to have it in the .env
