### ISSUE TITLE
Error: must be real number, not NoneType[BUG]

### ISSUE THREAD

**Issue by J3rr1ck** [FujiwaraChoki/MoneyPrinter#238]
hey there this was running fine for me up till today when I get the following error 
` [+] Subtitles generated.
[+] Combining videos...
[+] Each clip will be maximum 16.834 seconds long.
Moviepy - Building video ../temp/15f19b6b-162c-41c1-984c-929229e78142.mp4.
Moviepy - Writing video ../temp/15f19b6b-162c-41c1-984c-929229e78142.mp4

[-] Error: must be real number, not NoneType
INFO:werkzeug:127.0.0.1 - - [17/Feb/2024 11:01:52] "POST /api/generate HTTP/1.1" 200 -
`
Seems like all the videos are valid? any ideas?

**Comment by FujiwaraChoki** [comment]
Does this always happen or not?

**Comment by FujiwaraChoki** [comment]
Sorry, not sure what the problem is :(

It might be an indentation error with the if/else statements.

**Comment by StreamLightt** [comment]
On my windows laptot I also had the error. 
I fixed it by running those lines on my anaconda env : 
```
pip uninstall moviepy decorator 
pip install moviepy
```
If it can help anyone 😄
