### ISSUE TITLE
[BUG] No videos found to download

### ISSUE THREAD

**Issue by divmxnd0x** [FujiwaraChoki/MoneyPrinter#241]
Can't generate a single video due to:

Generated 5 search terms: sport stock videos, athletic footage, sports highlights, sports action clips, sports b-roll
        => "sport stock videos" found 0 Videos
        => "athletic footage" found 0 Videos
        => "sports highlights" found 0 Videos
        => "sports action clips" found 0 Videos
        => "sports b-roll" found 0 Videos
[-] No videos found to download.

Try to generate a video

**Expected behavior**
Video should be generated

 - OS: Windows 11
 - Python Version 3.11

**Comment by FujiwaraChoki** [comment]
Look through the other issues
