### ISSUE TITLE
[BUG][root@anonymous Backend]# python main.py   File "main.py", line 159     print(colored(f"[+] Downloading {len(video_urls)} videos...", "blue"))                                                                ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 125540947** [FujiwaraChoki/MoneyPrinter#242]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - Browser [e.g. chrome, edge]
 - Python Version [e.g. 3.9]

**Additional context**
[root@anonymous Backend]# python main.py
  File "main.py", line 159
    print(colored(f"[+] Downloading {len(video_urls)} videos...", "blue"))
                                                               ^
SyntaxError: invalid syntax

**Comment by FujiwaraChoki** [comment]
Not a bug, you probably changed something you shouldn't have.
