### ISSUE TITLE
[BUG] "No videos found to download."

### ISSUE THREAD

**Issue by Serback-Stable** [FujiwaraChoki/MoneyPrinter#243]
Good morning, this is my first time using github so I'm going to use the stock bug template, if I'm missing something please tell me, I'll add it asap.

**Describe the bug**
Basically after configuring both the front end and the backend and launching them, I'm getting this problem: "No videos found to download" before that, it tries to search for this terms, but it can't find anything (0 videos):
 
Generated 5 search terms: movies stock videos, cinematic stock footage, film clips, movie scenes, Hollywood footage
        => "movies stock videos" found 0 Videos
        => "cinematic stock footage" found 0 Videos
        => "film clips" found 0 Videos
        => "movie scenes" found 0 Videos
        => "Hollywood footage" found 0 Videos
[-] No videos found to download.
Also, I'm not getting any kind of mp4 output 

**To Reproduce**
1. [Go to '...'](http://localhost:3000/)
2. Generate output
3. 
4. Get this error

**Expected behavior**
MP4 File output

**Screenshots**
1 screenshot that shows 2 failed attemps.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox]
 - Python Version [Python 3.12.2]
![Screenshot 2024-03-16 142911](https://github.com/FujiwaraChoki/MoneyPrinter/assets/163655717/5624b595-e4ce-4030-8b7d-91d8c80292fa)

**Comment by Serback-Stable** [comment]
I forgot to add this, everytime I try to generate a file, it shows this, I do not know if it is normal: INFO:undetected_chromedriver.patcher:patching driver executable C:\Users\Enzo\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe

**Comment by Krisseck** [comment]
The video urls have changed in Pexels API.

In file `Backend/search.py`, line 48, change the string `com/external` to `loc=external`

I'm considering making a fork

**Comment by Serback-Stable** [comment]
> The video urls have changed in Pexels API.
> 
> In file `Backend/search.py`, line 48, change the string `com/external` to `loc=external`
> 
> I'm considering making a fork

Unfortunatly it did not change much, It can now rarely make 1 video, but for most imputes no videos get found. I think I'll try with MoneyPrinter V2, but if you have any other idea on how to fix it, it would be nice.

**Comment by Troptrap** [comment]
The best way to grab Pexels videos is not from the API itself, but constructing the url using ID of video. The end result looking like this:
`https://www.pexels.com/video/4916733/download/`
where the numbers are the ID

**Comment by Troptrap** [comment]
> I forgot to add this, everytime I try to generate a file, it shows this, I do not know if it is normal: INFO:undetected_chromedriver.patcher:patching driver executable C:\Users\Enzo\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe

This one is normal behavior. It comes from g4f (gpt for free) which uses a headless browser in background. That message is telling you that it uses a special driver for browser. It needs that to scrape websites like a human

**Comment by ipharksai** [comment]
Hey @FujiwaraChoki - just as a clarification for me, i keep running into these problems and all these issues are just closed by you with no further comment. Does that mean the issue is solved and what we experience is a new issue? Should we open new issues?

**Comment by FujiwaraChoki** [comment]
You're talking about separate problems in the same issue, and when once gets solved or clarified, I will close the issue. As @Troptrap mentioned, this has nothing to do with MoneyPrinter, rather `g4f`, if updating to the latest version doesn't help, then open an issue there, not here.

@ipharksai 

Also, I'm not a full-time maintainer, so stuff like this depends on the community 💯

**Comment by ipharksai** [comment]
Just to clarify, I was not criticizing you, I'm new to all that and just kept running into issues and was not sure if I should open new issues or not.

Sorry if that came over as rude!

**Comment by FujiwaraChoki** [comment]
> Just to clarify, I was not criticizing you, I'm new to all that and just kept running into issues and was not sure if I should open new issues or not.
> 
> Sorry if that came over as rude!

I didn't take it as rudeness, I was merely explaining ..
