### ISSUE TITLE
[BUG] It says that i dont have access to GPT-4 or it dosent exist but actually i paid for it

### ISSUE THREAD

**Issue by AlexKa03** [FujiwaraChoki/MoneyPrinter#245]
**Describe the bug**
When select from advanced GPT-4 it does give the error i descirbed and provided a screenshot. I alredy paid for GPT-4

**To Reproduce**
1. Go to **_Show Advanced Options_**
2. Click on **_AI Model drop down menu_**
3. Scroll down to **_OpenAI GPT-4_**
![cmd_hlYSR1c4jS](https://github.com/FujiwaraChoki/MoneyPrinter/assets/65862735/01cc76e7-2c30-4912-833d-15590921908f)

**Expected behavior**
It should just be able to use this AI model

**Screenshots**
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/65862735/baec81d1-2069-4467-bd96-d155013f51bf)
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/65862735/01cc76e7-2c30-4912-833d-15590921908f)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Python Version [3.12.2]

**Comment by CyZhang2023** [comment]
Openai API key for GPT4 and GTP4-Tubro-Preview is another bill, not using ChatGPT4 website. You can check the billing of your OpeanAI account on https://platform.openai.com/
