### ISSUE TITLE
[BUG] No videos found to download and it oppens new window in incognito in windows

### ISSUE THREAD

**Issue by AlexKa03** [FujiwaraChoki/MoneyPrinter#247]
**Describe the bug**
I reinstalled the whole software, because i had some problems with the whole pc. Now when i try to generate video it gives the error of "No videos found to download". I alredy changed the `string com/external `to `loc=external`. Before it worked with no problem! It opens new window in incognito for chrome which it didnt made before.

**To Reproduce**
1. Go to the localhost site
2. Click on Generate

**Expected behavior**
It shouldn't have this behaviour, it should work

**Screenshots**
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/65862735/a2576b0f-c1de-4484-bdd7-e1836d8f8c7d)

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Browser [Chrome]
 - Python Version [3.12.2]

**Comment by Togoyang** [comment]
same error

**Comment by NekoNesaprotu** [comment]
Hey, go into Backend/search.py and change ".com/external" to ".com/video-files" in this line - `if ".com/external" in video["link"]:` . Worked for me

**Comment by Togoyang** [comment]
> Hey, go into Backend/search.py and change ".com/external" to ".com/video-files" in this line - `if ".com/external" in video["link"]:` . Worked for me

It works! You are my hero!
