### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ClareXUse** [FujiwaraChoki/MoneyPrinter#248]
**Describe the bug**

**To Reproduce**
I followed the guide and then successfully open the webui ,while I try to input the prompt and click the generate botton, the error occurs that
 "Could not retrieve stock videos: Failed to perform, curl: (28) Failed to connect to you.com port 443 after 21284 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details."
**Expected behavior**
the code would run and generate videos

**Screenshots**
![1712321417521](https://github.com/FujiwaraChoki/MoneyPrinter/assets/113915977/c6e560bb-1a4a-4484-9d4e-b30ed6c43d74)

**Additional context**
seemed like is the network problem,but after I changed the Vpn for several times,the situation does not improved.. does anyone has the same problem?

**Comment by liuchuan0yufeng** [comment]
I have the same problem, have you solved it?

**Comment by FujiwaraChoki** [comment]
Try replacing `You` with another Provider [here](https://github.com/FujiwaraChoki/MoneyPrinter/blob/3ef6f3d70dca742e6ff027189fd156bd88de9ceb/Backend/gpt.py#L43).

**Comment by ClareXUse** [comment]
Sorry, I'm not very familiar with this area. Could you please tell me some replaceable content?

**Comment by FujiwaraChoki** [comment]
> Sorry, I'm not very familiar with this area. Could you please tell me some replaceable content?

Check the Providers in the `g4f` repository, you'll have a list of options there.

**Comment by FujiwaraChoki** [comment]
I will close this issue now, since I haven't heard anything back.

**Comment by william20210206** [comment]
same
