### ISSUE TITLE
[BUG] Link for Popular TT songs not work

### ISSUE THREAD

**Issue by alexandresanlim** [FujiwaraChoki/MoneyPrinter#249]
This link on description isn't working :
https://filebin.net/klylrens0uk2pnrg/drive-download-20240209T180019Z-001.zip

**Comment by FujiwaraChoki** [comment]
https://www.swisstransfer.com/d/d1bbfb04-b546-472b-a864-1c324f1e5bc9

**Comment by AlexKa03** [comment]
This link dosent work too

**Comment by Szymok** [comment]
Can someone reupload please?
