### ISSUE TITLE
RetryeProvider Failed

### ISSUE THREAD

**Issue by trashhme** [FujiwaraChoki/MoneyPrinter#25]
When i use the generate button, opens an chrome tab, go to "https://chatgpt4online.org/chat/" close and got that error.

![imagem_2024-02-07_071402378](https://github.com/FujiwaraChoki/MoneyPrinter/assets/106495219/0e0f3fa0-ef0a-4b5e-89a5-06ebd9a400c0)

**Comment by trashhme** [comment]
The error is in the version of the g4f i excluded the newest version and downloaded what you use "0.2.0.4" now it works fine.

**Comment by trashhme** [comment]
@FujiwaraChoki

**Comment by FujiwaraChoki** [comment]
This is not an issue with MoneyPrinter, but with the `g4f` package.

**Comment by trashhme** [comment]
yes, i know i just want to let the information here.
