### ISSUE TITLE
[BUG] This voice is unavailable right now

### ISSUE THREAD

**Issue by CengizhanYurdakul** [FujiwaraChoki/MoneyPrinter#250]
**Describe the bug**
[-] This voice is unavailable right now

**To Reproduce**
Selected Ghost Face, English US - Male 1 and peaceful voices. But TTS not responding.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 - Python Version: 3.11.0

**Comment by FujiwaraChoki** [comment]
Choose another voice. This is an issue with the Provider, not MP.
