### ISSUE TITLE
[BUG] Backend start with an error

### ISSUE THREAD

**Issue by NalaGinrut** [FujiwaraChoki/MoneyPrinter#254]
**To Reproduce**
```bash
python3 Backend/main.py
```

It throws:
***ERROR:utils:Error occurred while checking environment variables: can only concatenate str (not "NoneType") to str***

**Comment by NalaGinrut** [comment]
I entered the `Backend` directory, however it's the same result.
I'm sure `python3` is from the virtualenv local path.

**Comment by FujiwaraChoki** [comment]
Send me a screenshot of your project structure and .env file, blur out sensitive information.

**Comment by NalaGinrut** [comment]
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/19734/2d4ba055-63a5-42d8-8635-2d6a0fe30122)

**Comment by FujiwaraChoki** [comment]
Not ls, but tree command

**Comment by NalaGinrut** [comment]
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/19734/eb4f0675-e3a9-4536-85b1-102f263d25ec)

**Comment by NalaGinrut** [comment]
I removed it to show the tree to you, otherwise there're too many results.

**Comment by NalaGinrut** [comment]
oh, you mean the instance of ".env.example"? 
I thought `.env` was the common name of `virtualenv` generated.

**Comment by NalaGinrut** [comment]
Works like charming now! Thanks!
