### ISSUE TITLE
Error: Response 403: Cloudflare detected

### ISSUE THREAD

**Issue by bqio** [FujiwaraChoki/MoneyPrinter#257]
I get an error when generating.
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/45086516/6b9cc631-9342-4883-9517-be978e421345)

**Comment by FujiwaraChoki** [comment]
Try using a VPN

**Comment by AlexKa03** [comment]
Still not working. Recomend us VPN that you know works please, other providers is not a option since every other provider is broken.

**Comment by FujiwaraChoki** [comment]
I have done so many times in other issues, look through those beforehand.

**Comment by FujiwaraChoki** [comment]
Closing as no resp from OP

**Comment by AlexKa03** [comment]
There is no issue related to VPN or CloudFlare :)
To get rid out of the most errors I had to rewrite 40% of the code and other stuff, guess after you made a website you stopped supporting the original local version.
