### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jakubziebin** [FujiwaraChoki/MoneyPrinter#259]
![image](https://github.com/user-attachments/assets/95cc478a-4df9-4d92-9e2c-8f4d62de5e5d)
I got an error while using gemini, did anyone have the same problem?

**Comment by AntonyZ89** [comment]
same here, any fix?

**Comment by shaheryarashfaq-bluescarfai** [comment]
Getting same error on gpt as well

**Comment by shaheryar003** [comment]
@FujiwaraChoki kindly lookinto it

**Comment by FujiwaraChoki** [comment]
@shaheryar003 Kindly open a PR.

**Comment by shaheryar003** [comment]
@FujiwaraChoki i dont know how to fix the issue, nor i have fixed it, so thats why issue was raised here, why open a PR?

**Comment by FujiwaraChoki** [comment]
@shaheryar003 If you want something fixed or a new feature, do it yourself.

**Comment by FujiwaraChoki** [comment]
#260
