### ISSUE TITLE
[BUG] [-] Error: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by techcow2** [FujiwaraChoki/MoneyPrinter#260]
First time user. Everything looks correct until I get this error when clicking generate: 

```
localhost:3000 says

Could not retrieve stock videos: Expecting value: line 1 column 1 (char
0)
```
```
[-] Error: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [17/Sep/2024 10:28:11] "POST /api/generate HTTP/1.1" 200 -
```

**Comment by FujiwaraChoki** [comment]
I reverted the latest commit, could you check again? Thanks.

**Comment by techcow2** [comment]
> I reverted the latest commit, could you check again? Thanks.

`Could not retrieve stock videos: 'NoneType' object has no attribute 'group'` `[*] GPT returned an unformatted response. Attempting to clean...
[-] Error: 'NoneType' object has no attribute 'group'
INFO:werkzeug:127.0.0.1 - - [17/Sep/2024 12:03:31] "POST /api/generate HTTP/1.1" 200 -`

**Comment by FujiwaraChoki** [comment]
At least this issue is fixed. The error you're facing is pretty common though.. I recommend just searching for an issue that mentions a fix.

**Comment by FujiwaraChoki** [comment]
Will close now..
