### ISSUE TITLE
[BUG] issue when I click generate 

### ISSUE THREAD

**Issue by Reddington2133** [FujiwaraChoki/MoneyPrinter#262]
![image](https://github.com/user-attachments/assets/466049ff-d041-4c44-bedf-5bdb732b9321)

**Comment by Joly0** [comment]
I have the same error. I am trying to run it in docker using the provided docker-compose and dockerfile

**Comment by Kingfire4545** [comment]
I have that same error. I thought it was something wrong with the requirements, but everything was installed with no problem.

**Comment by FujiwaraChoki** [comment]
Do share the logs, I can not help you with just the error.

**Comment by FujiwaraChoki** [comment]
Closing no response

**Comment by Kingfire4545** [comment]
I apologize for the very late response. Where can I find the logs?
