### ISSUE TITLE
[BUG] songs/music download link no working!

### ISSUE THREAD

**Issue by fxgurv** [FujiwaraChoki/MoneyPrinter#265]
[BUG] songs/music download link no working! can you please update it.

**Comment by FujiwaraChoki** [comment]
Unfortunately I do not have the songs stored in my PC anymore, as I got myself a new one.

**Comment by fxgurv** [comment]
sad....
i can download but the problem is your collectin was awesome, those were popular music collection which is a little bit time consuming because finding downloading all one by one sucks! maybe your community have that collection ?
