### ISSUE TITLE
[BUG] unable to join discord

### ISSUE THREAD

**Issue by fxgurv** [FujiwaraChoki/MoneyPrinter#266]
unable to join discord server

**Comment by fxgurv** [comment]
![image](https://github.com/user-attachments/assets/c49326aa-ac3b-4254-a710-32f3cc676eb3)

**Comment by fxgurv** [comment]
i've tried with 2 accounts but both having same issue 
new account as well as old account but did not worked

maybe u can add me ?
user id: 994665059617869864
username: asonacademy

**Comment by FujiwaraChoki** [comment]
> i've tried with 2 accounts but both having same issue new account as well as old account but did not worked
> 
> maybe u can add me ? user id: 994665059617869864 username: asonacademy

Sent you a friend Request.
