### ISSUE TITLE
[BUG] Unable to get tiktok session ID?

### ISSUE THREAD

**Issue by mastachef** [FujiwaraChoki/MoneyPrinter#268]
Cant get tiktok session ID so how can I use this without it?

**Comment by FujiwaraChoki** [comment]
Not a bug; reopen with correct slug.

**Comment by mastachef** [comment]
> Not a bug; reopen with correct slug.

Slug?

**Comment by FujiwaraChoki** [comment]
Sorry - Issue Title.
