### ISSUE TITLE
MoviePY can't detect ImageMagick binary (windows)

### ISSUE THREAD

**Issue by NoobFullStack** [FujiwaraChoki/MoneyPrinter#27]
**Describe the bug**
Sometimes the Backend/main.py can't be started and I receive the following errors: 

```
(venv) PS E:\Development\Python\yt-automate\Backend> python main.py
Traceback (most recent call last):
  File "E:\Development\Python\yt-automate\Backend\main.py", line 4, in <module>
    from video import *
  File "E:\Development\Python\yt-automate\Backend\video.py", line 8, in <module>
    from moviepy.editor import *
  File "E:\Development\Python\yt-automate\venv\lib\site-packages\moviepy\editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip     
  File "E:\Development\Python\yt-automate\venv\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "E:\Development\Python\yt-automate\venv\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "E:\Development\Python\yt-automate\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 7, in <module>   
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "E:\Development\Python\yt-automate\venv\lib\site-packages\moviepy\audio\io\ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "E:\Development\Python\yt-automate\venv\lib\site-packages\moviepy\config.py", line 67, in <module>
    raise IOError(
OSError: ImageMagick binary cannot be found at "C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe" # Download from https://imagemagick.org/script/download.php
```

**To Reproduce**
1. Clone repo
2. Create venv and install requirements.txt
3. cd /Backend and `python main.py`

**Expected behavior**
Starting of the backend process

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python 3.10.6 (venv)

**Additional context**
It's feels kinda random.. I had the same issue yesterday too, when testing in between.. It was working before, and all the sudden it stopped working. I deleted the venv and re-installed requirements.txt in new venv.. It started working again, but now it doesn't. 

I have verified the install paths mentioned in the OSError, the file is still there.

**Comment by 1NoobDev** [comment]
Inside my `.env` I have: 
`IMAGEMAGICK_BINARY="C:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\magick.exe"`

Also, after reading some similar issues online, tried to hardcore the path inside main.py: 
`change_settings({"IMAGEMAGICK_BINARY": r"C:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\magick.exe"})`

But same error notification..

**Comment by FujiwaraChoki** [comment]
Check out this thread: https://stackoverflow.com/questions/51928807/moviepy-cant-detect-imagemagick-binary-on-windows

I'm not quite sure what the cause of this issue is, but maybe try re-installing ImageMagick.

**Comment by 1NoobDev** [comment]
I found the same article, re-installed using the settings mentioned (including: `legacy utilities`). But that didn't resolve. Still have the same error as mentioned above. Will try to find solution and update the issue when found.

**Comment by dallascrilley** [comment]
I was experiencing this issue but was able to fix it. The path that worked for me on mac was:
/opt/homebrew/opt/imagemagick/bin/magick

Downloading the binary and loading it from the MoneyPrinter directory didn't work for me for some reason (could have been permissions)

**Comment by dVaGaymer** [comment]
I had a similar problem in Ubuntu (WSL) and to solve it I just gave all file permissions to the magic executable file

**Comment by titusthef0x** [comment]
Works with single slashes for me on Windows 11:

IMAGEMAGICK_BINARY="C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe" # Download from https://imagemagick.org/script/download.php

**Comment by 1NoobDev** [comment]
> Works with single slashes for me on Windows 11:
> 
> IMAGEMAGICK_BINARY="C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe" # Download from https://imagemagick.org/script/download.php

I had it like this initially and worked the whole evening.. until I restarted vscode it didn't work anymore.. I think it's more related to ImageMagick, and not this yt shorts generator epo.. thanks for the response though 💪
