### ISSUE TITLE
major feature change - Full-on autopilot with db / csv inputs

### ISSUE THREAD

**Issue by 1NoobDev** [FujiwaraChoki/MoneyPrinter#32]
Hi there, 

I want to create a full-on autopilot mode, that will take inputs from a .db or .csv file, rather than manually inputting them one-by-one via the frontend. Since this is a major change to the repo, just thought to ask your opinion about this if it makes sense or is even desired, and maybe any requirements you'd like to add into. 

Kind regards,

**Comment by evolite** [comment]
what i did was remove the frontend, remove the flask webserver. change chatgpt to instead just figure out a topic on its own, return that as input for image finding.

now when i run the script it just egenrates a random video :P

I suggest you fork the repo and make whatver you want

**Comment by 1NoobDev** [comment]
as per readme `For major changes, please open an issue first to discuss what you would like to change.`; hence I ask if FujiwaraChoki is open for such a major change to his repo.

**Comment by FujiwaraChoki** [comment]
Honestly, I'm just trying to keep it stable right now, and there were some issues with the PR you pushed that I didn't quite notice.

Maybe in the future, but for now I'll close this issue.

**Comment by 1NoobDev** [comment]
> Honestly, I'm just trying to keep it stable right now, and there were some issues with the PR you pushed that I didn't quite notice.
> 
> Maybe in the future, but for now I'll close this issue.

Those issues came from the edits committed just before my PR, not related to the yt uploading functionality.. sorry for not checking them either.. keep up the good work 💪💯
