### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PiotrTyrakowski** [FujiwaraChoki/MoneyPrinter#36]
**Describe the bug**
i am not able to get videos using pexels

**To Reproduce**
just pressed create video on front end

**Screenshots**
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/19981478/42f110eb-3aa0-4036-af71-f0da9b242497)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chorme
 - Python Version [e.g. 3.12]

**Additional context**
When i create testing function like this, everything works fine.
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/19981478/317509cd-faa2-417a-9975-f3ad81cb63db)

**Comment by FujiwaraChoki** [comment]
Please execute the `tree` command and show me the output. I suspect you have your Pexels API Key in the correct `.env` file, but the location of it is wrong.

**Comment by PiotrTyrakowski** [comment]
screen of my file tree:
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/19981478/86d8fa4b-6bdd-40cf-bb7d-09f5435f120a)

also is this correct?
IMAGEMAGICK_BINARY="C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe" 

output of tree:
Folder PATH listing for volume OS
Volume serial number is 4457-E8E0
C:.
├───.github
│   └───ISSUE_TEMPLATE
├───.venv
│   ├───Include
│   ├───Lib
│   │   └───site-packages
│   │       ├───aiohttp
│   │       │   ├───.hash
│   │       │   └───__pycache__
│   │       ├───aiohttp-3.9.3.dist-info
│   │       ├───aiosignal
│   │       │   └───__pycache__
│   │       ├───aiosignal-1.3.1.dist-info
│   │       ├───annotated_types
│   │       │   └───__pycache__
│   │       ├───annotated_types-0.6.0.dist-info
│   │       │   └───licenses
│   │       ├───anyio
│   │       │   ├───abc
│   │       │   │   └───__pycache__
│   │       │   ├───streams
│   │       │   │   └───__pycache__
│   │       │   ├───_backends
│   │       │   │   └───__pycache__
│   │       │   ├───_core
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───anyio-4.2.0.dist-info
│   │       ├───assemblyai
│   │       │   └───__pycache__
│   │       ├───assemblyai-0.20.2.dist-info
│   │       ├───attr
│   │       │   └───__pycache__
│   │       ├───attrs
│   │       │   └───__pycache__
│   │       ├───attrs-23.2.0.dist-info
│   │       │   └───licenses
│   │       ├───blinker
│   │       │   └───__pycache__
│   │       ├───blinker-1.7.0.dist-info
│   │       ├───Brotli-1.1.0.dist-info
│   │       ├───certifi
│   │       │   └───__pycache__
│   │       ├───certifi-2024.2.2.dist-info
│   │       ├───cffi
│   │       │   └───__pycache__
│   │       ├───cffi-1.16.0.dist-info
│   │       ├───charset_normalizer
│   │       │   ├───cli
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───charset_normalizer-3.3.2.dist-info
│   │       ├───click
│   │       │   └───__pycache__
│   │       ├───click-8.1.7.dist-info
│   │       ├───colorama
│   │       │   ├───tests
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───colorama-0.4.6.dist-info
│   │       │   └───licenses
│   │       ├───decorator-4.4.2.dist-info
│   │       ├───dotenv
│   │       │   └───__pycache__
│   │       ├───flask
│   │       │   ├───json
│   │       │   │   └───__pycache__
│   │       │   ├───sansio
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───flask-3.0.2.dist-info
│   │       ├───flask_cors
│   │       │   └───__pycache__
│   │       ├───Flask_Cors-4.0.0.dist-info
│   │       ├───frozenlist
│   │       │   └───__pycache__
│   │       ├───frozenlist-1.4.1.dist-info
│   │       ├───g4f
│   │       │   ├───api
│   │       │   │   └───__pycache__
│   │       │   ├───gui
│   │       │   │   ├───client
│   │       │   │   │   ├───css
│   │       │   │   │   ├───html
│   │       │   │   │   ├───img
│   │       │   │   │   └───js
│   │       │   │   ├───server
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───Provider
│   │       │   │   ├───bing
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───deprecated
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───needs_auth
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───npm
│   │       │   │   │   └───node_modules
│   │       │   │   │       └───crypto-js
│   │       │   │   ├───selenium
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───unfinished
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───g4f-0.2.1.0.dist-info
│   │       ├───h11
│   │       │   ├───tests
│   │       │   │   ├───data
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───h11-0.14.0.dist-info
│   │       ├───httpcore
│   │       │   ├───_async
│   │       │   │   └───__pycache__
│   │       │   ├───_backends
│   │       │   │   └───__pycache__
│   │       │   ├───_sync
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───httpcore-1.0.2.dist-info
│   │       │   └───licenses
│   │       ├───httpx
│   │       │   ├───_transports
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───httpx-0.26.0.dist-info
│   │       │   └───licenses
│   │       ├───idna
│   │       │   └───__pycache__
│   │       ├───idna-3.6.dist-info
│   │       ├───imageio
│   │       │   ├───config
│   │       │   │   └───__pycache__
│   │       │   ├───core
│   │       │   │   └───__pycache__
│   │       │   ├───plugins
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───imageio-2.33.1.dist-info
│   │       ├───imageio_ffmpeg
│   │       │   ├───binaries
│   │       │   └───__pycache__
│   │       ├───imageio_ffmpeg-0.4.9.dist-info
│   │       ├───itsdangerous
│   │       │   └───__pycache__
│   │       ├───itsdangerous-2.1.2.dist-info
│   │       ├───jinja2
│   │       │   └───__pycache__
│   │       ├───Jinja2-3.1.3.dist-info
│   │       ├───markupsafe
│   │       │   └───__pycache__
│   │       ├───MarkupSafe-2.1.5.dist-info
│   │       ├───moviepy
│   │       │   ├───audio
│   │       │   │   ├───fx
│   │       │   │   │   ├───all
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───io
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───tools
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───video
│   │       │   │   ├───compositing
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───fx
│   │       │   │   │   ├───all
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───io
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───tools
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───moviepy-1.0.3.dist-info
│   │       ├───multidict
│   │       │   └───__pycache__
│   │       ├───multidict-6.0.5.dist-info
│   │       ├───numpy
│   │       │   ├───array_api
│   │       │   │   ├───tests
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───compat
│   │       │   │   ├───tests
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───core
│   │       │   │   ├───include
│   │       │   │   │   └───numpy
│   │       │   │   │       └───random
│   │       │   │   ├───lib
│   │       │   │   │   └───npy-pkg-config
│   │       │   │   ├───tests
│   │       │   │   │   ├───data
│   │       │   │   │   ├───examples
│   │       │   │   │   │   ├───cython
│   │       │   │   │   │   │   └───__pycache__
│   │       │   │   │   │   └───limited_api
│   │       │   │   │   │       └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───doc
│   │       │   │   └───__pycache__
│   │       │   ├───f2py
│   │       │   │   ├───src
│   │       │   │   ├───tests
│   │       │   │   │   ├───src
│   │       │   │   │   │   ├───abstract_interface
│   │       │   │   │   │   ├───array_from_pyobj
│   │       │   │   │   │   ├───assumed_shape
│   │       │   │   │   │   ├───block_docstring
│   │       │   │   │   │   ├───callback
│   │       │   │   │   │   ├───cli
│   │       │   │   │   │   ├───common
│   │       │   │   │   │   ├───crackfortran
│   │       │   │   │   │   ├───f2cmap
│   │       │   │   │   │   ├───isocintrin
│   │       │   │   │   │   ├───kind
│   │       │   │   │   │   ├───mixed
│   │       │   │   │   │   ├───module_data
│   │       │   │   │   │   ├───negative_bounds
│   │       │   │   │   │   ├───parameter
│   │       │   │   │   │   ├───quoted_character
│   │       │   │   │   │   ├───regression
│   │       │   │   │   │   │   └───gh25337
│   │       │   │   │   │   ├───return_character
│   │       │   │   │   │   ├───return_complex
│   │       │   │   │   │   ├───return_integer
│   │       │   │   │   │   ├───return_logical
│   │       │   │   │   │   ├───return_real
│   │       │   │   │   │   ├───size
│   │       │   │   │   │   ├───string
│   │       │   │   │   │   └───value_attrspec
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───_backends
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───fft
│   │       │   │   ├───tests
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───lib
│   │       │   │   ├───tests
│   │       │   │   │   ├───data
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───linalg
│   │       │   │   ├───tests
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───ma
│   │       │   │   ├───tests
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───matrixlib
│   │       │   │   ├───tests
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───polynomial
│   │       │   │   ├───tests
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───random
│   │       │   │   ├───lib
│   │       │   │   ├───tests
│   │       │   │   │   ├───data
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───_examples
│   │       │   │   │   ├───cffi
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───cython
│   │       │   │   │   └───numba
│   │       │   │   │       └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───testing
│   │       │   │   ├───tests
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───_private
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───tests
│   │       │   │   └───__pycache__
│   │       │   ├───typing
│   │       │   │   ├───tests
│   │       │   │   │   ├───data
│   │       │   │   │   │   ├───fail
│   │       │   │   │   │   ├───misc
│   │       │   │   │   │   ├───pass
│   │       │   │   │   │   │   └───__pycache__
│   │       │   │   │   │   └───reveal
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───_core
│   │       │   │   └───__pycache__
│   │       │   ├───_pyinstaller
│   │       │   │   └───__pycache__
│   │       │   ├───_typing
│   │       │   │   └───__pycache__
│   │       │   ├───_utils
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───numpy-1.26.4.dist-info
│   │       ├───numpy.libs
│   │       ├───outcome
│   │       │   └───__pycache__
│   │       ├───outcome-1.3.0.post0.dist-info
│   │       ├───PIL
│   │       │   └───__pycache__
│   │       ├───Pillow-9.5.0.dist-info
│   │       ├───pip
│   │       │   ├───_internal
│   │       │   │   ├───cli
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───commands
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───distributions
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───index
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───locations
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───metadata
│   │       │   │   │   ├───importlib
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───models
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───network
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───operations
│   │       │   │   │   ├───build
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───install
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───req
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───resolution
│   │       │   │   │   ├───legacy
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───resolvelib
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───utils
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───vcs
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───_vendor
│   │       │   │   ├───cachecontrol
│   │       │   │   │   ├───caches
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───certifi
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───chardet
│   │       │   │   │   ├───cli
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───metadata
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───colorama
│   │       │   │   │   ├───tests
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───distlib
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───distro
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───idna
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───msgpack
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───packaging
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───pkg_resources
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───platformdirs
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───pygments
│   │       │   │   │   ├───filters
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───formatters
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───lexers
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───styles
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───pyparsing
│   │       │   │   │   ├───diagram
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───pyproject_hooks
│   │       │   │   │   ├───_in_process
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───requests
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───resolvelib
│   │       │   │   │   ├───compat
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───rich
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───tenacity
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───tomli
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───truststore
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───urllib3
│   │       │   │   │   ├───contrib
│   │       │   │   │   │   ├───_securetransport
│   │       │   │   │   │   │   └───__pycache__
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───packages
│   │       │   │   │   │   ├───backports
│   │       │   │   │   │   │   └───__pycache__
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───util
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───webencodings
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───pip-24.0.dist-info
│   │       ├───pkg_resources
│   │       │   ├───extern
│   │       │   │   └───__pycache__
│   │       │   ├───_vendor
│   │       │   │   ├───importlib_resources
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───jaraco
│   │       │   │   │   ├───text
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───more_itertools
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───packaging
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───platformdirs
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───platformdirs
│   │       │   └───__pycache__
│   │       ├───platformdirs-4.2.0.dist-info
│   │       │   └───licenses
│   │       ├───playsound-1.3.0.dist-info
│   │       ├───proglog
│   │       │   └───__pycache__
│   │       ├───proglog-0.1.10.dist-info
│   │       ├───pycparser
│   │       │   ├───ply
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───pycparser-2.21.dist-info
│   │       ├───pydantic
│   │       │   ├───deprecated
│   │       │   │   └───__pycache__
│   │       │   ├───plugin
│   │       │   │   └───__pycache__
│   │       │   ├───v1
│   │       │   │   └───__pycache__
│   │       │   ├───_internal
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───pydantic-2.6.1.dist-info
│   │       │   └───licenses
│   │       ├───pydantic_core
│   │       │   └───__pycache__
│   │       ├───pydantic_core-2.16.2.dist-info
│   │       │   └───license_files
│   │       ├───PySocks-1.7.1.dist-info
│   │       ├───python_dotenv-1.0.1.dist-info
│   │       ├───requests
│   │       │   └───__pycache__
│   │       ├───requests-2.31.0.dist-info
│   │       ├───selenium
│   │       │   ├───common
│   │       │   │   └───__pycache__
│   │       │   ├───webdriver
│   │       │   │   ├───chrome
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───chromium
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───common
│   │       │   │   │   ├───actions
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───bidi
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   ├───devtools
│   │       │   │   │   │   ├───v119
│   │       │   │   │   │   │   └───__pycache__
│   │       │   │   │   │   ├───v120
│   │       │   │   │   │   │   └───__pycache__
│   │       │   │   │   │   ├───v121
│   │       │   │   │   │   │   └───__pycache__
│   │       │   │   │   │   └───v85
│   │       │   │   │   │       └───__pycache__
│   │       │   │   │   ├───linux
│   │       │   │   │   ├───macos
│   │       │   │   │   ├───windows
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───edge
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───firefox
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───ie
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───remote
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───safari
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───support
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───webkitgtk
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───wpewebkit
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───selenium-4.17.2.dist-info
│   │       ├───setuptools
│   │       │   ├───command
│   │       │   │   └───__pycache__
│   │       │   ├───config
│   │       │   │   ├───_validate_pyproject
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───extern
│   │       │   │   └───__pycache__
│   │       │   ├───_distutils
│   │       │   │   ├───command
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───_vendor
│   │       │   │   ├───importlib_metadata
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───importlib_resources
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───jaraco
│   │       │   │   │   ├───text
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───more_itertools
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───packaging
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───tomli
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───setuptools-69.0.3.dist-info
│   │       ├───sniffio
│   │       │   ├───_tests
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───sniffio-1.3.0.dist-info
│   │       ├───sortedcontainers
│   │       │   └───__pycache__
│   │       ├───sortedcontainers-2.4.0.dist-info
│   │       ├───srt-3.5.3.dist-info
│   │       ├───srt_equalizer
│   │       │   └───__pycache__
│   │       ├───srt_equalizer-0.1.8.dist-info
│   │       ├───srt_tools
│   │       │   └───__pycache__
│   │       ├───termcolor
│   │       │   └───__pycache__
│   │       ├───termcolor-2.4.0.dist-info
│   │       │   └───licenses
│   │       ├───tests
│   │       │   ├───unit
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───tqdm
│   │       │   ├───contrib
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───tqdm-4.66.1.dist-info
│   │       ├───trio
│   │       │   ├───testing
│   │       │   │   └───__pycache__
│   │       │   ├───_core
│   │       │   │   ├───_tests
│   │       │   │   │   ├───type_tests
│   │       │   │   │   │   └───__pycache__
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───_subprocess_platform
│   │       │   │   └───__pycache__
│   │       │   ├───_tests
│   │       │   │   ├───tools
│   │       │   │   │   └───__pycache__
│   │       │   │   ├───type_tests
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───_tools
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───trio-0.24.0.dist-info
│   │       ├───trio_websocket
│   │       │   └───__pycache__
│   │       ├───trio_websocket-0.11.1.dist-info
│   │       ├───typing_extensions-4.9.0.dist-info
│   │       ├───undetected_chromedriver
│   │       │   └───__pycache__
│   │       ├───undetected_chromedriver-3.5.4.dist-info
│   │       ├───urllib3
│   │       │   ├───contrib
│   │       │   │   ├───emscripten
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   ├───util
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───urllib3-2.2.0.dist-info
│   │       │   └───licenses
│   │       ├───websockets
│   │       │   ├───extensions
│   │       │   │   └───__pycache__
│   │       │   ├───legacy
│   │       │   │   └───__pycache__
│   │       │   ├───sync
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───websockets-12.0.dist-info
│   │       ├───werkzeug
│   │       │   ├───datastructures
│   │       │   │   └───__pycache__
│   │       │   ├───debug
│   │       │   │   ├───shared
│   │       │   │   └───__pycache__
│   │       │   ├───middleware
│   │       │   │   └───__pycache__
│   │       │   ├───routing
│   │       │   │   └───__pycache__
│   │       │   ├───sansio
│   │       │   │   └───__pycache__
│   │       │   ├───wrappers
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───werkzeug-3.0.1.dist-info
│   │       ├───wheel
│   │       │   ├───cli
│   │       │   │   └───__pycache__
│   │       │   ├───vendored
│   │       │   │   ├───packaging
│   │       │   │   │   └───__pycache__
│   │       │   │   └───__pycache__
│   │       │   └───__pycache__
│   │       ├───wheel-0.42.0.dist-info
│   │       ├───wsproto
│   │       │   └───__pycache__
│   │       ├───wsproto-1.2.0.dist-info
│   │       ├───yarl
│   │       │   └───__pycache__
│   │       ├───yarl-1.9.4.dist-info
│   │       ├───_distutils_hack
│   │       │   └───__pycache__
│   │       └───__pycache__
│   └───Scripts
├───.vscode
├───Backend
│   └───__pycache__
├───fonts
├───Frontend
└───temp

**Comment by FujiwaraChoki** [comment]
Did you fix it?

**Comment by PiotrTyrakowski** [comment]
Nope

**Comment by FujiwaraChoki** [comment]
Not sure, but now that I think about it most people having random issues, are people who use venvs, maybe try and do it locally?

**Comment by PiotrTyrakowski** [comment]
problem is not with .env file, i have acces to my PIXELS_API_KEY (i can print it) but still i have this error.
also i want to know if this path is correct: 
IMAGEMAGICK_BINARY="C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe"
