### ISSUE TITLE
[BUG] "Voiceover" is inserted into Subtitles, Script and actual Voiceover

### ISSUE THREAD

**Issue by radry** [FujiwaraChoki/MoneyPrinter#38]
**Describe the bug**
The resulting video has "Voiceover" as subtitle and actual Voice at the beginning of each new clip within the output.

**Expected behavior**
No "Voiceover" in the result

**Screenshots**
![3](https://github.com/FujiwaraChoki/MoneyPrinter/assets/8878118/96f87580-07f6-4ef9-9f16-82170e3d56ef)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Python Version 3.11

**Additional context**
I suspect this is caused by the ChatGPT output, because "Voiceover" already appears in the debug output when it initially generates the text.

**Comment by 1NoobDev** [comment]
Try to tweak the prompt (inside gpt.py) as such it doesn't include those words.

**Comment by radry** [comment]
> Try to tweak the prompt (inside gpt.py) as such it doesn't include those words.

Wouldn't it be more reliable to just parse the script and delete all "voiceover"  before it is further used to generate subtitles and voice?

**Comment by FujiwaraChoki** [comment]
> > Try to tweak the prompt (inside gpt.py) as such it doesn't include those words.
> 
> Wouldn't it be more reliable to just parse the script and delete all "voiceover" before it is further used to generate subtitles and voice?

No, because it's not just "voiceover". There are a lot of keywords, and what if someone's script includes voiceover?
