### ISSUE TITLE
[BUG] Vertical source videos are cropped and zoomed in instead of just resized.

### ISSUE THREAD

**Issue by radry** [FujiwaraChoki/MoneyPrinter#39]
**Describe the bug**
When a vertical video is downloaded it crops a very zoomed in part and resized that.

**Expected behavior**
Only resize without cropping when the source is a vertical video already.

**Screenshots**
Source:
![1](https://github.com/FujiwaraChoki/MoneyPrinter/assets/8878118/a1e5114f-b7eb-4ae3-a309-17b500b9843a)

Result in output:
![2](https://github.com/FujiwaraChoki/MoneyPrinter/assets/8878118/5a670635-4726-4670-b6b9-be7e1e3a869c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Python Version 3.11

**Additional context**
The cropping in general is not very good currently. For example sometimes a horizontal video gets squished instead of jsut cropped, but that's another issue.

I suggest using ffmpeg directly (can be used over moviepy too: https://zulko.github.io/moviepy/ref/ffmpeg.html )  to resize each clip before cropping. Also a check if the video even needs to be cropped (simple IF check to detect vertical video).

**Comment by FujiwaraChoki** [comment]
Feel free to open a PR, as I'm currently busy.
