### ISSUE TITLE
No module named 'g4f'

### ISSUE THREAD

**Issue by PylenVance** [FujiwaraChoki/MoneyPrinter#4]
Tried doing pip install g4f although no difference upon startup

**Comment by FujiwaraChoki** [comment]
Then you're probably using the wrong interpreter to execute the script, try using `python` instead of `python3` when installing, so:

```bash
python -m pip install -U g4f
```

**Comment by PylenVance** [comment]
Thanks fixed that ,although upon fixing it it now returns this error when creating a video
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/126495424/6867c446-97b4-4b8f-ae39-b82a32f2c226)

**Comment by FujiwaraChoki** [comment]
This is probably because you supplied the wrong ImageMagick Path, it should point to the .exe file called magick.exe, also make sure to use double back slash on windows.

See one of the closed issues talking about this error

**Comment by PylenVance** [comment]
Sorry but where do i insert the path?

**Comment by FujiwaraChoki** [comment]
Bro did you read the instructions 💀
Copy contents from .env.example to .env, and fill out the values.

**Comment by FujiwaraChoki** [comment]
Did that solve your problem?
