### ISSUE TITLE
the program cant find stock videos

### ISSUE THREAD

**Issue by Aikpo** [FujiwaraChoki/MoneyPrinter#45]
[-] No Videos found.
{'status': 401, 'code': 'Unauthorized'}
        =>
[-] No Videos found.
{'status': 401, 'code': 'Unauthorized'}
        =>
[-] No Videos found.
{'status': 401, 'code': 'Unauthorized'}
        =>
[-] No Videos found.
{'status': 401, 'code': 'Unauthorized'}
        =>
[-] No Videos found.
{'status': 401, 'code': 'Unauthorized'}

**Comment by FujiwaraChoki** [comment]
Follow instructions step-by-step.
