### ISSUE TITLE
i recloned the git rep but i still have this issue

### ISSUE THREAD

**Issue by Aikpo** [FujiwaraChoki/MoneyPrinter#49]
it says this [+] Creating subtitles locally
[+] Subtitles generated.
[+] Combining videos...
[-] Error: float division by zero

**Comment by FujiwaraChoki** [comment]
Show us your file tree and your .env file (censor out sensitive parts).

**Comment by radry** [comment]
You need to link to the actual magick.exe, not just the path.

**Comment by N3xi0** [comment]
I got the same issue :
it says this [+] Creating subtitles locally
[+] Subtitles generated.
[]
[-] Error: float division by zero
and i did everything right with the"IMAGEMAGICK_BINARY="C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\\magick.exe" # Download from https://imagemagick.org/script/download.php" and its still didnt work
