### ISSUE TITLE
Cant find module named "Playsound"

### ISSUE THREAD

**Issue by TypicalNexus** [FujiwaraChoki/MoneyPrinter#5]
I having an issue when I run the python main.py it says "Cant find playsound module"

i tried doing python3 main.py. Now idk why it doesnt work

![image_2024-02-02_100559476](https://github.com/FujiwaraChoki/MoneyPrinter/assets/98793742/cd95ca7a-1de3-44a5-bac0-a6b62d6632b7)

**Comment by TypicalNexus** [comment]
yes i did install the playsound module

**Comment by FujiwaraChoki** [comment]
> yes i did install the playsound module

Can you try installing the requirements with pip3?

Maybe that will change something, as the interpreter is maybe mixed up.

**Comment by FujiwaraChoki** [comment]
> I had the same problem but fixed it by using pip install pip==21.3.1 and then trying again, I have not a single clue why it worked since I was at that stage where you just do random things and hope you dont break it even further but it worked for some reason

Appreciate it, a lot of modules are simply broken nowadays, it's extremely weird.

**Comment by TypicalNexus** [comment]
Also when getting the api keys do I just put my download path to imagemagick?
