### ISSUE TITLE
I found another error 

### ISSUE THREAD

**Issue by Aikpo** [FujiwaraChoki/MoneyPrinter#51]
here it is [+] Creating subtitles locally
[-] Error: Expected contiguous start of match or end of input at char 1400, but started at char 1735 (unmatched content: '9\n0:01:34,600 --> 0:01\nAs technology advances, new industries and roles emerge\n\n10\n0:01 --> 0:01:58,700\nFor example, the development and maintenance of AI systems require skilled professionals in fields like machine learning, data science, and software engineering.\n\nMoreover, AI can augment human capabilities and improve productivity')

**Comment by FujiwaraChoki** [comment]
Stop opening new issues. Mostly they are not issues with the code, rather with your environment. They are also poorly defined and include little to no information for anyone to be able to help you. I still appreciate you trying to help and make this project better.
