### ISSUE TITLE
[BUG] Getting Error 

### ISSUE THREAD

**Issue by xDope7137** [FujiwaraChoki/MoneyPrinter#53]
**Describe the bug**
I am getting "An Error Occurred. Please try again later" error.

**To Reproduce**
1. Make sure backend and frontend servers are on
2. Try to click generate

**Expected behavior**
work?

**Screenshots**
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/58150973/075836e5-922b-43f3-b173-d179e61774fe)

**Desktop (please complete the following information):**
 - OS: Windows Server 2022
 - Browser : Brave
 - Python Version v3.12.0

**Comment by FujiwaraChoki** [comment]
Please look into the console of the Browser, and see if there is anything. Maybe try going to localhost:3000 instead of your IP (probably isn't the issue).

**Comment by radry** [comment]
No problem here on Windows 10 and Python 3.11

It might be a problem with your installation.

**Comment by xDope7137** [comment]
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/58150973/b00edd4a-34a2-453c-aa61-83e48be477de)

**Comment by xDope7137** [comment]
> Maybe try going to localhost:3000 instead of your IP (probably isn't the issue).

That fixed it thank you.
