### ISSUE TITLE
[BUG][-] Error: cannot access local variable 'ASSEMBLY_AI_API_KEY' where it is not associated with a value

### ISSUE THREAD

**Issue by Skeyelab** [FujiwaraChoki/MoneyPrinter#54]
**Describe the bug**
I am repeatedly getting the following error:

```[-] Error: cannot access local variable 'ASSEMBLY_AI_API_KEY' where it is not associated with a value```

I do have my ASSEMBLY_AI_API_KEY ENV variable set

**Comment by FujiwaraChoki** [comment]
Apologies, this is a bug in the code I believe.

**Comment by FujiwaraChoki** [comment]
Could you pull & try again?

**Comment by Skeyelab** [comment]
@FujiwaraChoki - all good now!  I opened a few PRs that will help with some dev sanity. :)
