### ISSUE TITLE
Error: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Boing7678** [FujiwaraChoki/MoneyPrinter#6]
hi, sorry if this is a simple question, but when running it, it sometimes gives me Error: 'NoneType' object has no attribute 'group' and sometimes [-] Error: 'videos' does anyone know how to fix this? thanks!
![grafik](https://github.com/FujiwaraChoki/MoneyPrinter/assets/157311680/c1c3f677-fb36-421b-a2bb-ba849b8bcd6c)
![grafik](https://github.com/FujiwaraChoki/MoneyPrinter/assets/157311680/7a62bffa-affe-497f-a176-bcc4cc81134d)
![grafik](https://github.com/FujiwaraChoki/MoneyPrinter/assets/157311680/586b80af-1b0f-437d-a489-0e7bb5e36be9)

[+] Cleaned ../temp/ directory
[+] Cleaned ../subtitles/ directory
[Video to be generated]
   Subject: testing video
**Testing Video Script**

"In this video, we will conduct a series of tests to demonstrate the performance and functionality of our new product. First, we will examine the durability of the materials used by subjecting the product to various impact tests. Next, we will evaluate the product's reliability by conducting stress tests under different environmental conditions. Additionally, we will showcase the product's user interface and highlight its intuitive design through a series of demonstrations. Finally, we will conclude by summarizing our findings and highlighting the key benefits of the product. Stay tuned as we put our product to the test and uncover its capabilities."
```json
[
  "product testing video",
  "performance testing footage",
  "reliability test stock video",
  "stress test demonstration",
  "product durability showcase"
]
```
[*] GPT returned an unformatted response. Attempting to clean...
[-] Error: 'NoneType' object has no attribute 'group'
127.0.0.1 - - [02/Feb/2024 21:39:43] "POST /api/generate HTTP/1.1" 200 -

tree:
Auflistung der Ordnerpfade für Volume Data
Volumeseriennummer : E82D-14AA
D:.
├───Backend
│   └───__pycache__
├───fonts
├───Frontend
├───subtitles
└───temp

in .env
IMAGEMAGICK_BINARY="C:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\magick.exe" # Download from https://imagemagick.org/script/download.php

(I did double backslash but github formats it as a single one for some reason)

**Comment by FujiwaraChoki** [comment]
I assume the other Env variables are set correctly?

**Comment by Boing7678** [comment]
![grafik](https://github.com/FujiwaraChoki/MoneyPrinter/assets/157311680/b10f4985-d9d3-45be-ae52-163a25ff8c30)
this is the whole file, i didn't show the other ones since I wasn't sure wether you could log in into my tiktok using the session ID

**Comment by TypicalNexus** [comment]
i having the same issue

**Comment by FujiwaraChoki** [comment]
Does this always happen, or just sometimes?

**Comment by Boing7678** [comment]
It seems to be random which I get, but it's always one of them. I haven't been able to create a working video yet.

**Comment by FujiwaraChoki** [comment]
Try re-cloning `MoneyPrinter`, re-entering the Environment Variables, and then see if anything changes. I don't really think this is an issue with the code, it's difficult to say at this point. Just make sure that your Pexels API Key is set 100% correctly.

**Comment by Salty-Coder** [comment]
Had this issue, but only when GPT occasionally returns the json as a markdown string like this: 

\```json
[
example
]
\```

when it should be like this:

[
example
]

**Comment by FujiwaraChoki** [comment]
> Had this issue, but only when GPT occasionally returns the json as a markdown string like this:
> 
> ```json [ example ] ```
> 
> when it should be like this:
> 
> [ example ]

Yeah, this is pretty easy to fix.

**Comment by Salty-Coder** [comment]
Does this program still work? I never successfully managed to generate a video. It managed to get the search term array, then throw an error.

**Comment by FujiwaraChoki** [comment]
> Does this program still work? I never successfully managed to generate a video. It managed to get the search term array, then throw an error.

Of course it works, it has for many, I just refactored the search term extraction using Regex, pull and try again.

**Comment by tafolau** [comment]
Issue still there.

```
[*] GPT returned an unformatted response. Attempting to clean...
[-] Error: 'NoneType' object has no attribute 'group'
```

**Comment by FujiwaraChoki** [comment]
Switch to another Provider from `g4f`. If it still doesn't work, I recommend opening an issue in the `g4f` repository.

**Comment by Salty-Coder** [comment]
> Switch to another Provider from `g4f`. If it still doesn't work, I recommend opening an issue in the `g4f` repository.

I can't remember exactly, but I believe switching g4f provider was how I fixed it in the end.

**Comment by tafolau** [comment]
Here's a solution:

`    try:
        search_terms = json.loads(response)
        if not isinstance(search_terms, list) or not all(isinstance(term, str) for term in search_terms):
            raise ValueError("Response is not a list of strings.")

    except (json.JSONDecodeError, ValueError):
        print(colored("[*] GPT returned an unformatted response. Attempting to clean...", "yellow"))

        # Get everything between the first and last square brackets
        response = "[" + response[response.find("[") + 1:response.rfind("]")] + "]"

        try:
            search_terms = json.loads(response)
        except json.JSONDecodeError:
            print(colored("[-] Could not parse response.", "red"))
            return []`
