### ISSUE TITLE
[BUG] chatgpt4online Blocked and causing error

### ISSUE THREAD

**Issue by raniaamina** [FujiwaraChoki/MoneyPrinter#64]
**Describe the bug**
The process stoped at this step;

```
[*] GPT returned an unformatted response. Attempting to clean...
[-] Could not parse response.
[-] Error: the JSON object must be str, bytes or bytearray, not list
127.0.0.1 - - [08/Feb/2024 12:54:09] "POST /api/generate HTTP/1.1" 200 -
```

 

**To Reproduce**
1. Start backend and frontend
2. Just input a topic, then click generate
4. Error happen

![gambar](https://github.com/FujiwaraChoki/MoneyPrinter/assets/22146607/ae3ad39c-6c0d-40c7-b902-d8813b34747f)

**Expected behavior**
No error on the process. It recently happen.

**Screenshots**
![gambar](https://github.com/FujiwaraChoki/MoneyPrinter/assets/22146607/588f22f4-1ce9-44c9-a39b-de83bc7d2055)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Python Version 3.11.7

**Additional context**
i tried to use some vpn but get same results

**Comment by FujiwaraChoki** [comment]
This happens sometimes, you will have to restart. That means that the `g4f` package was unable to generate search terms for the stock videos. Another thing you could try is enabling a VPN (ProtonVPN recommended). If that still doesn't work, I recommend opening an issue in the [`gpt4free`](https://github.com/xtekky/gpt4free/) repository.

**Comment by raniaamina** [comment]
I used protonvpn and my own vpn when testing, but still get same error
