### ISSUE TITLE
[BUG] Cleaning unformatted ChatGPT response fails

### ISSUE THREAD

**Issue by radry** [FujiwaraChoki/MoneyPrinter#70]
**Describe the bug**

```
[*] GPT returned an unformatted response. Attempting to clean...
[-] Could not parse response.
[-] Error: the JSON object must be str, bytes or bytearray, not list
```

**Expected behavior**
Cleaning attempts succeds, if not then queries chatgpt again

**Comment by SJTheGreat06** [comment]
Facing the same problem

**Comment by RazinReaz** [comment]
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/55131094/18f5e898-eb17-4307-b489-24ef5b347824)
Same here

**Comment by radry** [comment]
The problem occurs when we try to json.load a result that isn't proper json. Looking into a solution now.
