### ISSUE TITLE
[BUG] If video is already vertical, the resizing stretches the video.

### ISSUE THREAD

**Issue by Syycorax** [FujiwaraChoki/MoneyPrinter#72]
**Describe the bug**
If a downloaded video is already in a vertical format, the resizing step stretches it, making it unusable
**Steps to reproduce**
Try generating until you get a video that is already in a vertical format (2160x4096 in my case)

**Expected behavior**
If the video is already in the vertical format, don't resize it

**Screenshots**
Generated video
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/54723548/16b04acd-2010-43fc-be8c-4fcbe8334c99)
Original video
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/54723548/85669a74-a0c4-4a98-8ccc-2c8a2761b78e)

**Comment by FujiwaraChoki** [comment]
@radry Mind taking a look at this?

**Comment by radry** [comment]
Hmm this shouldn't happen. Are you on the latest version?  

Currently it will only skip the cropping step if it's exactly 9:16 (0,5265) aspect ratio. This video has 0,5273 but even if it didn't skip it, the cropping should ensure the result is the correct aspect ratio.

**Comment by Syycorax** [comment]
I cloned the repo something like 30 minutes ago

**Comment by radry** [comment]
I will look at it later today, I'm currently working on another improvement.

**Comment by PiotrTyrakowski** [comment]
The bug occurs when video is taller than 9:16 format, like 9:18.
Here is fix in video.py near line 160:

ratio = round((clip.w/clip.h), 4)

# if video is wider than 9:16
if ratio < 0.5625:
    clip = crop(clip, width=clip.w, height=round(clip.w/0.5625), \
                x_center=clip.w / 2, \
                y_center=clip.h / 2)
    
# if video is taller than 9:16
if ratio > 0.5625:
    clip = crop(clip, width=round(0.5625*clip.h), height=clip.h, \
                x_center=clip.w / 2, \
                y_center=clip.h / 2)


clip = clip.resize((1080, 1920))

clips.append(clip)

**Comment by radry** [comment]
@PiotrTyrakowski 
That's not a clean solution. If do `crop(clip, width=clip.w, height=round(clip.w/0.5625), `
the result is not 9:16 and will be distorted when resizing afterwards to 1080x1920
