### ISSUE TITLE
[BUG] Audio Glitches from concatenate_audioclips

### ISSUE THREAD

**Issue by Vaughn1234** [FujiwaraChoki/MoneyPrinter#77]
I am getting weird audio fragments inbetween the audio clips. Searching online lead me here https://github.com/Zulko/moviepy/issues/1936#issuecomment-1740785869 but the suggested solution doesn't fix it either. I've also attempted adding audio fade-in and -out to the audio clips which seems to alleviate the issue a bit but still no full fix

**Comment by FujiwaraChoki** [comment]
Could you share the video, and what you changed?

**Comment by Vaughn1234** [comment]
Here is an example video: https://cdn.discordapp.com/attachments/1070765422275731476/1205155443102453760/output.mp4?ex=65d75778&is=65c4e278&hm=03567f6f3ff24690b997d39ec2d9eb7406c0ef47bf10bdc5066b007a20011f11&

You can hear the artifacts at 0:07 and at the very end after the final word. What I mainly changed are to use videos from a local folder instead of searching for stock videos and adjusting the aspect ratio of those videos. I am also using the openAI library instead of g4f.

**Comment by nayan924** [comment]
concatenate clips and then set audio later

**Comment by Vaughn1234** [comment]
> concatenate clips and then set audio later

This is already what is happening and I didn't change it. The video clips are being concatenated, then the audio clips are being concatenated and then they are combined. The audio artifacts do not exist in the individual audio clips, they are only introduced in the concatenated audio file

**Comment by Cyberghost999** [comment]
Use this after importing your audio clip `audio_clip = audio_clip.subclip(0, audio_clip.duration - 0.05)` . This fixed the problem for me.
