### ISSUE TITLE
Error: RetryProvider failed

### ISSUE THREAD

**Issue by ricardofalc** [FujiwaraChoki/MoneyPrinter#8]
First time setting everything up, i get this error.
Am i missing packages? I have installed the requirements.txt.
But i still had to manually install a lot of packages myself before being able to run the backend.

- python-dotenv
- srt_equalizer
- setuptools
- wheel

```
[Video to be generated]
   Subject: Short video about marathon running
[-] Error: RetryProvider failed:
ChatgptNext: ClientResponseError: 429, message='Too Many Requests', url=URL('https://chat.fstha.com/api/openai/v1/chat/completions')
You: ClientResponseError: 403, message='Forbidden', url=URL('https://you.com/api/streamingSearch?q=%0A++++Generate+a+script+for+a+video,+depending+on+the+subject+of+the+video.%0A++++Subject:+Short+video+about+marathon+running%0A%0A++++The+script+is+to+be+returned+as+a+string.%0A%0A++++Here+is+an+example+of+a+string:%0A++++%22This+is+an+example+string.%22%0A%0A++++Do+not+under+any+circumstance+refernce+this+prompt+in+your+response.%0A%0A++++Get+straight+to+the+point,+don't+start+with+unnecessary+things+like,+%22welcome+to+this+video%22.%0A%0A++++Obviously,+the+script+should+be+related+to+the+subject+of+the+video.%0A%0A++++ONLY+RETURN+THE+RAW+SCRIPT.+DO+NOT+RETURN+ANYTHING+ELSE.%0A++++&domain=youchat&chat=')
GeekGpt: HTTPError: 521 Server Error:  for url: https://ai.fakeopen.com/v1/chat/completions
FakeGpt: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://linux.do/t/topic/1051')
ChatgptDemoAi: ClientResponseError: 400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://chat.chatgptdemo.ai/wp-json/mwai-ui/v1/chats/submit')
FreeGpt: AttributeError: 'StreamResponse' object has no attribute 'iter_content'
ChatgptDemo: ClientResponseError: 500, message='Internal Server Error', url=URL('https://chat.chatgptdemo.net/chat_api_stream')
Chatgpt4Online: MissingRequirementsError: Install "undetected_chromedriver" and "platformdirs" package
127.0.0.1 - - [04/Feb/2024 14:06:16] "POST /api/generate HTTP/1.1" 200 -
```

![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/90937422/ea3c241e-7365-4994-85c8-6498edef578a)

**Comment by FujiwaraChoki** [comment]
> ```
> 
> [Video to be generated]
> 
>    Subject: Short video about marathon running
> 
> [-] Error: RetryProvider failed:
> 
> ChatgptNext: ClientResponseError: 429, message='Too Many Requests', url=URL('https://chat.fstha.com/api/openai/v1/chat/completions')
> 
> You: ClientResponseError: 403, message='Forbidden', url=URL('https://you.com/api/streamingSearch?q=%0A++++Generate+a+script+for+a+video,+depending+on+the+subject+of+the+video.%0A++++Subject:+Short+video+about+marathon+running%0A%0A++++The+script+is+to+be+returned+as+a+string.%0A%0A++++Here+is+an+example+of+a+string:%0A++++%22This+is+an+example+string.%22%0A%0A++++Do+not+under+any+circumstance+refernce+this+prompt+in+your+response.%0A%0A++++Get+straight+to+the+point,+don't+start+with+unnecessary+things+like,+%22welcome+to+this+video%22.%0A%0A++++Obviously,+the+script+should+be+related+to+the+subject+of+the+video.%0A%0A++++ONLY+RETURN+THE+RAW+SCRIPT.+DO+NOT+RETURN+ANYTHING+ELSE.%0A++++&domain=youchat&chat=')
> 
> GeekGpt: HTTPError: 521 Server Error:  for url: https://ai.fakeopen.com/v1/chat/completions
> 
> FakeGpt: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://linux.do/t/topic/1051')
> 
> ChatgptDemoAi: ClientResponseError: 400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://chat.chatgptdemo.ai/wp-json/mwai-ui/v1/chats/submit')
> 
> FreeGpt: AttributeError: 'StreamResponse' object has no attribute 'iter_content'
> 
> ChatgptDemo: ClientResponseError: 500, message='Internal Server Error', url=URL('https://chat.chatgptdemo.net/chat_api_stream')
> 
> Chatgpt4Online: MissingRequirementsError: Install "undetected_chromedriver" and "platformdirs" package
> 
> 127.0.0.1 - - [04/Feb/2024 14:06:16] "POST /api/generate HTTP/1.1" 200 -
> 
> ```

Visit xtekky/gpt4free on GitHub, there might be information regarding this problem. It should be fixed if you can just change the model from gpt_4 to a GPT 3.5 variant.

**Comment by FujiwaraChoki** [comment]
Also, I forgot to add these requirements to the list, will be adding them.

**Comment by ricardofalc** [comment]
So i need to setup gpt4free in a Docker container as instructed?

**Comment by FujiwaraChoki** [comment]
Not nessecarily, try replacing `g4f.models.gpt_35_turbo_16k_0613` with `g4f.models.gpt_4`

**Comment by ricardofalc** [comment]
I changed following in gpt.py:

`    # Generate search terms
    response = g4f.ChatCompletion.create(
        model=g4f.models.gpt_4,
        messages=[{"role": "user", "content": prompt}],
    )`
    
   Still same issue:
   
   
![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/90937422/8435b7ff-e9d7-419f-bb15-8af0c7817610)

**Comment by ricardofalc** [comment]
VPN + installed 
- platformdirs
- undetected_chromedriver

**Comment by lukas748** [comment]
I'm having the same issue, but already installed platformdirs and undetected_chromedriver.

**Comment by FujiwaraChoki** [comment]
> **VPN**

**Comment by FujiwaraChoki** [comment]
ProtonVPN should be fine.

**Comment by lukas748** [comment]
It worked fine! Thanks.

**Comment by rodrigogs** [comment]
So... I have to have a VPN? Is there another way? Could I use OpenAI API directly?
