### ISSUE TITLE
Limit length to 60 seconds (Youtube Shorts limit)

### ISSUE THREAD

**Issue by radry** [FujiwaraChoki/MoneyPrinter#81]
YT shorts has a limit of 60 seconds, however the video generated here can be way longer. 

edit: Maybe this can be done at the "source" by telling chatgpt to make the script a certain length. Will try that but open to other suggestions.

**Comment by giubaru** [comment]
Yes, I tried putting this in the `generate_script` prompt ` Generate a script for a 45 seconds video, depending on the subject of the video.` . It works generating videos from 45 secs to 57 secs.

**Comment by nayan924** [comment]
@FujiwaraChoki add fx adjust speed to 59999-clip.duration*1000 as speed factor, it will speed up the clip to be exactly within limits to be recognised as a short.

**Comment by nayan924** [comment]
why is it 3 minutes, my suggestion was for if its going little more than 1 minute, ur right, in addition to character limit of 1 minute script for cases where it goes little above, it can work.

**Comment by FujiwaraChoki** [comment]
Will be added
