### ISSUE TITLE
Face recognise and crop 9:16 keeping face

### ISSUE THREAD

**Issue by nayan924** [FujiwaraChoki/MoneyPrinter#83]
**Is your feature request related to a problem? Please describe.**
Not a problem per se

**Describe the solution you'd like**
Like opus clip, upload or give link of full length video, it download video, transcribe, cut parts in transcript, then chops video into sections, then maybe speaker diarisation, detect face, do vertical crop over the face, not sure how to detect which face is talking and audio of that segment matches to the person thats talking.

**Describe alternatives you've considered**
Opus clip is paid, and cuz these vids can't be monetised, not worthy to use a paid tool, lets make it ourselves.

**Additional context**
just crop vertical frame over the person thats talking.

**Comment by nayan924** [comment]
why not?

**Comment by FujiwaraChoki** [comment]
This is not the intended goal with this project - I made it simply for the technical aspect. Also there's absolutely no reason to implement Face Recognition into this.
