### ISSUE TITLE
[BUG] Error: RetryProvider failed:

### ISSUE THREAD

**Issue by jajunior** [FujiwaraChoki/MoneyPrinter#87]
Getting an error in the first step of video generation

[-] Error: RetryProvider failed:
FreeGpt: AttributeError: 'StreamResponse' object has no attribute 'iter_content'
You: ClientResponseError: 403, message='Forbidden', url=URL('https://you.com/api/streamingSearch?q=%0A++++Generate+a+script+for+a+video,+depending+on+the+subject+of+the+video.%0A++++Subject:+bauru%0A%0A++++The+script+is+to+be+returned+as+a+string.%0A%0A++++Here+is+an+example+of+a+string:%0A++++%22This+is+an+example+string.%22%0A%0A++++Do+not+under+any+circumstance+reference+this+prompt+in+your+response.%0A%0A++++Get+straight+to+the+point,+don't+start+with+unnecessary+things+like,+%22welcome+to+this+video%22.%0A%0A++++Obviously,+the+script+should+be+related+to+the+subject+of+the+video.%0A%0A++++ONLY+RETURN+THE+RAW+CONTENT+OF+THE+SCRIPT.+DO+NOT+INCLUDE+%22VOICEOVER%22,+%22NARRATOR%22+OR+SIMILAR+INDICATORS+OF+WHAT+SHOULD+BE+SPOKEN+AT+THE+BEGINNING+OF+EACH+PARAGRAPH+OR+LINE.%0A++++&domain=youchat&chat=')
ChatgptNext: ClientResponseError: 429, message='Too Many Requests', url=URL('https://chat.fstha.com/api/openai/v1/chat/completions')
Chatgpt4Online: TypeError: Binary Location Must be a String
ChatgptDemoAi: ClientResponseError: 404, message='Not Found', url=URL('https://chat.chatgptdemo.ai/wp-json/mwai-ui/v1/chats/submit')
FakeGpt: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://linux.do/t/topic/1051')
GeekGpt: HTTPError: 521 Server Error:  for url: https://ai.fakeopen.com/v1/chat/completions
ChatgptDemo: ClientResponseError: 500, message='Internal Server Error', url=URL('https://chat.chatgptdemo.net/chat_api_stream')

**Comment by FujiwaraChoki** [comment]
VPN

**Comment by jajunior** [comment]
I've tried with many VPN across multiple locations and still gives me this error.
