### ISSUE TITLE
Dockerfile Request

### ISSUE THREAD

**Issue by bbrooks870** [FujiwaraChoki/MoneyPrinter#97]
is any one working on its Dockerfile, will be very usefull to , run the script in One Go

**Comment by amad1101** [comment]
Could you do it ?

**Comment by bbrooks870** [comment]
nah but i can try with the help of chatgpt

**Comment by iStorry** [comment]
Dockerfile
```
FROM ubuntu:22.04

RUN apt-get update && apt-get install --no-install-recommends -y python3 \
    python3-dev python3-pip build-essential imagemagick

RUN pip3 install --upgrade pip

WORKDIR /app

ADD ./requirements.txt .
RUN pip3 install -r requirements.txt
RUN pip3 install celery[redis]

ADD ./backend ./backend
ADD ./frontend ./frontend
ADD ./fonts ./fonts
```


# Build docker image 
`docker build -t username/moneyprinter .`

docker-compose.yml
```
version: "3"
services:
  frontend:
    image: "username/moneyprinter"
    container_name: "frontend"
    ports:
      - "8001:8001"
    command: ["python3", "-m", "http.server", "8001", "--directory", "frontend"]
    restart: always
  backend:
    image: "username/moneyprinter"
    container_name: "backend"
    ports:
      - "8080:8080"
    command: ["python3", "backend/main.py"]
    environment:
      - ASSEMBLY_AI_API_KEY=
      - TIKTOK_SESSION_ID=
      - IMAGEMAGICK_BINARY=/usr/bin/convert # docker path
      - PEXELS_API_KEY=
    depends_on:
      - redis
      - frontend
    restart: always
```


@amad1101 @bbrooks870

**Comment by GregHilston** [comment]
@iStorry Have you ran this successfully? When running this stack, I'm seeing the follow error message from the backend service:

```
OSError: ImageMagick binary cannot be found at "/usr/bin/convert"
Traceback (most recent call last):
  File "/app/backend/main.py", line 4, in <module>
    from video import *
  File "/app/backend/video.py", line 9, in <module>
    from moviepy.editor import *
  File "/usr/local/lib/python3.10/dist-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/usr/local/lib/python3.10/dist-packages/moviepy/config.py", line 67, in <module>
    raise IOError(
OSError: ImageMagick binary cannot be found at "/usr/bin/convert"
```

**Comment by iStorry** [comment]
> @iStorry Have you ran this successfully? When running this stack, I'm seeing the follow error message from the backend service:
> 
> ```
> OSError: ImageMagick binary cannot be found at "/usr/bin/convert"
> Traceback (most recent call last):
>   File "/app/backend/main.py", line 4, in <module>
>     from video import *
>   File "/app/backend/video.py", line 9, in <module>
>     from moviepy.editor import *
>   File "/usr/local/lib/python3.10/dist-packages/moviepy/editor.py", line 36, in <module>
>     from .video.io.VideoFileClip import VideoFileClip
>   File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
>     from moviepy.audio.io.AudioFileClip import AudioFileClip
>   File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
>     from moviepy.audio.AudioClip import AudioClip
>   File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/AudioClip.py", line 7, in <module>
>     from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
>   File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
>     from moviepy.config import get_setting
>   File "/usr/local/lib/python3.10/dist-packages/moviepy/config.py", line 67, in <module>
>     raise IOError(
> OSError: ImageMagick binary cannot be found at "/usr/bin/convert"
> ```

![image](https://github.com/FujiwaraChoki/MoneyPrinter/assets/7252344/934193ea-da60-4faf-9961-b1babb7430f0)

It's seems to working fine for me are you building image by yourself?

**Comment by GregHilston** [comment]
Interesting.

Yes I am. I did not modify a single character in the Docker file, however I made a few minor adjustments that I did not think had any interference with the installation of or the path of inagemagik.

I can share the files later today but things i changed were pointing each docker compose service to a local build context and the very docker file you provided. I obviously provided my environment variable values and will be adding in a volume to more easily extract the output video.

I'll provide a follow up comment with exact files later today to see if you can spot my blunder

**Comment by iStorry** [comment]
@GregHilston Sure. but if you want to output video use flask itself 

```python
@app.route("/api/download/<video_id>", methods=["GET"])
def download(video_id: str):
    # Check vid in the temp folder
    # If it exists, return the file
    VIDEO_PATH = os.path.join(BASE_PATH, "temp", f"{video_id}.mp4")

    if not os.path.exists(VIDEO_PATH):
        return jsonify({"status": "error", "message": "Video not found!"})

    return send_file(VIDEO_PATH, as_attachment=True)
```

This is how I export videos.

You can add this to main.py and build your image.

**Comment by esteinborn** [comment]
Does this have a location from the docker-compose.yml file where it spits out the videos? seems like its spitting them out inside the container. Should we have a volume mapping to map into the container?

**Comment by iStorry** [comment]
> Does this have a location from the docker-compose.yml file where it spits out the videos? seems like its spitting them out inside the container. Should we have a volume mapping to map into the container?

@esteinborn You can map the volume as well. but I am using flask itself. See my above comment. 

I will update docker image with this.

**Comment by esteinborn** [comment]
is the output at `/temp`? I'm looking there and there are a bunch of mp4 files, but none of them have burned in subtitles or audio, seems like only the vimeo stock videos

**Comment by iStorry** [comment]
> is the output at `/temp`? I'm looking there and there are a bunch of mp4 files, but none of them have burned in subtitles or audio, seems like only the vimeo stock videos

output file would be "temp.mp4" as far as I remember.

**Comment by Bartixxx32** [comment]
> @esteinborn
> 
> > is the output at `/temp`? I'm looking there and there are a bunch of mp4 files, but none of them have burned in subtitles or audio, seems like only the vimeo stock videos
> 
> output file would be "temp.mp4" as far as I remember.

hey, i`m also same situation, theres no output in /temp

**Comment by esteinborn** [comment]
i get an error message at the end of generation:
```
2752/5224 [05:04<06:06,  6.75it/s, now=None]WARNING:py.warnings:/usr/local/lib/python3.10/dist-packages/moviepy/video/io/ffmpeg_reader.py:123: UserWarning: Warning: in file ../temp/4305080d-31e4-48f2-96d0-6f579938af0c.mp4, 24883200 bytes wanted but 0 bytes read,at frame 347/348, at time 14.47/14.49 sec. Using the last valid frame instead.
backend   |   warnings.warn("Warning: in file %s, "%(self.filename)+
```

**Comment by RicardoMonteiroSimoes** [comment]
This looks like it could be a good addition to the repo, one could even imagine a release action that builds the image and hosts it somewhere, but that's all up to the owner of this repo

**Comment by iStorry** [comment]
> > @esteinborn
> > > is the output at `/temp`? I'm looking there and there are a bunch of mp4 files, but none of them have burned in subtitles or audio, seems like only the vimeo stock videos
> > 
> > 
> > output file would be "temp.mp4" as far as I remember.
> 
> hey, i`m also same situation, theres no output in /temp

This is happening because of image magic path. I am working on fix.

**Comment by RicardoMonteiroSimoes** [comment]
> > > > @esteinborn
> > > > > is the output at `/temp`? I'm looking there and there are a bunch of mp4 files, but none of them have burned in subtitles or audio, seems like only the vimeo stock videos
> > > > 
> > > > 
> > > > output file would be "temp.mp4" as far as I remember.
> > > 
> > > 
> > > hey, i`m also same situation, theres no output in /temp
> > 
> > 
> > This is happening because of image magic path. I am working on fix.
> 
> I found out there is issue with merging final outputs video+audio, idk if thats docker issue or script itself. Btw found out that both audio and video is generated but its in /temp as random name and separate

That seems to be an issue I'm facing right now in a non-docker environment as well, see here:
https://github.com/FujiwaraChoki/MoneyPrinter/issues/119

**Comment by GregHilston** [comment]
> @GregHilston Sure. but if you want to output video use flask itself
> 
> ```python
> @app.route("/api/download/<video_id>", methods=["GET"])
> def download(video_id: str):
>     # Check vid in the temp folder
>     # If it exists, return the file
>     VIDEO_PATH = os.path.join(BASE_PATH, "temp", f"{video_id}.mp4")
> 
>     if not os.path.exists(VIDEO_PATH):
>         return jsonify({"status": "error", "message": "Video not found!"})
> 
>     return send_file(VIDEO_PATH, as_attachment=True)
> ```
> 
> This is how I export videos.
> 
> You can add this to main.py and build your image.

Ah, this is very smart, I am saddened by not thinking of this approach myself ha. I'll make this same modification my end. Do you just hit this endpoint raw, from say curl? Or did you add some connection to the frontend?

---

Here's my `Dockerfile`, which has slight modifications:

```docker
FROM ubuntu:22.04

RUN apt-get update && apt-get install --no-install-recommends -y python3 \
    python3-dev python3-pip build-essential imagemagick

RUN pip3 install --upgrade pip

WORKDIR /app

ADD ./MoneyPrinter/requirements.txt .
RUN pip3 install -r requirements.txt

ADD ./MoneyPrinter/Backend ./backend
ADD ./MoneyPrinter/Frontend ./frontend
ADD ./MoneyPrinter/fonts ./fonts
```

As for my `docker-compose.yaml` file, here it is:

```yaml
version: "3.7"

services:
  money-printer-frontend:
    build:
      context: ./money-printer
      dockerfile: Dockerfile
    container_name: "money-printer-frontend"
    ports:
      - "8001:8001"
    command: ["python3", "-m", "http.server", "8001", "--directory", "frontend"]
    restart: unless-stopped

  money-printer-backend:
    build:
      context: ./money-printer
      dockerfile: Dockerfile
    container_name: "money-printer-backend"
    ports:
      - "8080:8080"
    command: ["python3", "backend/main.py"]
    environment:
      - ASSEMBLY_AI_API_KEY=${SECRET_ASSEMBLY_AI_API_KEY}
      # - TIKTOK_SESSION_ID=
      - IMAGEMAGICK_BINARY="/usr/bin/convert" # path referring to inside container
      - PEXELS_API_KEY=${SECRET_PEXELS_API_KEY}
    volumes:
      - ${}
    depends_on:
      - money-printer-frontend
    restart: unless-stopped
```

The `${}` are just interpolation of environment variables that I had set. Here's my directory structure, which matters for `Dockerfile ADD` commands:

```
home-lab/
    money-printer/
        Dockerfile
        MoneyPrinter/ (this is the repo cloned)
        .gitignore
    docker-compose.yaml
```

@iStorry Do you see any blunder I'm made here?

**Comment by iStorry** [comment]
I've updated the Dockerfile and docker-compose.yml 

Please check this.
https://github.com/FujiwaraChoki/MoneyPrinter/issues/97#issuecomment-1935515102

**Comment by iStorry** [comment]
> Ah, this is very smart, I am saddened by not thinking of this approach myself ha. I'll make this same modification my end. Do you just hit this endpoint raw, from say curl? Or did you add some connection to the frontend?

I use the browser right now, also I have updated the docker-compose.yml for volume

I'm working with celery to make everything async so later I will implement this in frontend itself.

`IMAGEMAGICK_BINARY` this was having issue I fixed this in my new Dockerfile please check that.

https://github.com/FujiwaraChoki/MoneyPrinter/issues/97#issuecomment-1935515102

**Comment by iStorry** [comment]
> > > > > @esteinborn
> > > > > > is the output at `/temp`? I'm looking there and there are a bunch of mp4 files, but none of them have burned in subtitles or audio, seems like only the vimeo stock videos
> > > > > 
> > > > > 
> > > > > output file would be "temp.mp4" as far as I remember.
> > > > 
> > > > 
> > > > hey, i`m also same situation, theres no output in /temp
> > > 
> > > 
> > > This is happening because of image magic path. I am working on fix.
> > 
> > 
> > I found out there is issue with merging final outputs video+audio, idk if thats docker issue or script itself. Btw found out that both audio and video is generated but its in /temp as random name and separate
> 
> That seems to be an issue I'm facing right now in a non-docker environment as well, see here: #119

I am facing same issue I am looking into it.

**Comment by RicardoMonteiroSimoes** [comment]
> I've updated the Dockerfile and docker-compose.yml
> 
> Please check this. [#97 (comment)](https://github.com/FujiwaraChoki/MoneyPrinter/issues/97#issuecomment-1935515102)
> 
> Here is the new docker-compose.yml
> 
> ```
> version: "3"
> services:
>   frontend:
>     image: "istorry/moneyprinter:latest"
>     container_name: "frontend"
>     ports:
>       - "8001:8001"
>     command: ["python3", "-m", "http.server", "8001", "--directory", "frontend"]
>     restart: always
>   backend:
>     image: "istorry/moneyprinter:latest"
>     container_name: "backend"
>     ports:
>       - "8080:8080"
>     command: ["python3", "backend/main.py"]
>     volumes:
>       - ./files:/temp
>     environment:
>       - ASSEMBLY_AI_API_KEY=
>       - TIKTOK_SESSION_ID=
>       - IMAGEMAGICK_BINARY=/usr/local/bin/magick
>       - PEXELS_API_KEY=
>     depends_on:
>       - frontend
>     restart: always
> 
> volumes:
>   files:
> ```

Doesn't having to install magick locally defeat the purpose of the dockerfiles? It should be all contained inside of it, so that you can very literally just get the image, compose up and it's all ready

**Comment by GregHilston** [comment]
@RicardoMonteiroSimoes I think there's some confusion here. magick is installed in the container, and not the host OS. the path `/usr/local/bin/magick` refers to a path *inside the container*. See the updated dockerfile in the very quote you quoted

**Comment by RicardoMonteiroSimoes** [comment]
@GregHilston 

Ah, my bad, I wrongly interpreted the file, you're right :)

**Comment by iStorry** [comment]
> @GregHilston
> 
> Ah, my bad, I wrongly interpreted the file, you're right :)

I found the fix regarding no-audio i am right now verifying it.

**Comment by RicardoMonteiroSimoes** [comment]
> > @GregHilston
> > Ah, my bad, I wrongly interpreted the file, you're right :)
> 
> I found the fix regarding no-audio i am right now verifying it.

Care to elaborate on the specifics? Seems to be impacting non-docker usages as well

**Comment by esteinborn** [comment]
the output video it just created for me is 3:21 long. That is too long for a youtube short. It did grab a LOT of information from GPT on the term I used. 

> YouTube Shorts can be up to 60 seconds in length. This can be several 15-second videos combined or one continuous video. -YouTube

**Comment by Aikpo** [comment]
so if i change my pythin version it will generate audio again bc i have the same problem ? no docker

**Comment by RicardoMonteiroSimoes** [comment]
> the output video it just created for me is 3:21 long. That is too long for a youtube short. It did grab a LOT of information from GPT on the term I used.
> 
> > YouTube Shorts can be up to 60 seconds in length. This can be several 15-second videos combined or one continuous video. -YouTube

there are several PRs trying to address that, the issue is the GPT response which tends to get absurdly long.

**Comment by iStorry** [comment]
Can someone try this 

Docker image = `istorry/moneyprinter:audiofix`

**Comment by Bartixxx32** [comment]
> Can someone try this 
> 
> Docker image = `istorry/moneyprinter:audiofix`

Could you please provide the dockerfile or repo with those builds? We really dont know whats in this image ;)

**Comment by RicardoMonteiroSimoes** [comment]
It probably makes sense to move this docker image stuff into it's own PR so we can review it and see the changes

**Comment by iStorry** [comment]
> > Can someone try this
> > Docker image = `istorry/moneyprinter:audiofix`
> 
> Could you please provide the dockerfile or repo with those builds? We really dont know whats in this image ;)

Nothing much i changed python version 

```
FROM ubuntu:22.04

RUN apt-get update && apt-get install --no-install-recommends -y python3.11 \
    python3-dev python3-pip build-essential \
    autoconf pkg-config wget ghostscript

RUN apt-get update && apt-get install -y wget && \
    apt-get install -y build-essential curl libpng-dev && \
    wget https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.0-31.tar.gz && \
    tar xzf 7.1.0-31.tar.gz && \
    rm 7.1.0-31.tar.gz && \
    apt-get clean && \
    apt-get autoremove

RUN sh ./ImageMagick-7.1.0-31/configure --prefix=/usr/local --with-bzlib=yes --with-fontconfig=yes --with-freetype=yes --with-gslib=yes --with-gvc=yes --with-jpeg=yes --with-jp2=yes --with-png=yes --with-tiff=yes --with-xml=yes --with-gs-font-dir=yes && \
    make -j && make install && ldconfig /usr/local/lib/

WORKDIR /tmp


RUN pip install --upgrade pip

WORKDIR /app

ADD ./requirements.txt .
RUN pip install -r requirements.txt

ADD ./Backend ./backend
ADD ./Frontend ./frontend
ADD ./fonts ./fonts
```

@Bartixxx32

**Comment by Bartixxx32** [comment]
> > > Can someone try this
> > > Docker image = `istorry/moneyprinter:audiofix`
> > 
> > Could you please provide the dockerfile or repo with those builds? We really dont know whats in this image ;)
> 
> Nothing much i changed python version 
> 
> ```
> FROM ubuntu:22.04
> 
> RUN apt-get update && apt-get install --no-install-recommends -y python3.11 \
>     python3-dev python3-pip build-essential \
>     autoconf pkg-config wget ghostscript
> 
> RUN apt-get update && apt-get install -y wget && \
>     apt-get install -y build-essential curl libpng-dev && \
>     wget https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.0-31.tar.gz && \
>     tar xzf 7.1.0-31.tar.gz && \
>     rm 7.1.0-31.tar.gz && \
>     apt-get clean && \
>     apt-get autoremove
> 
> RUN sh ./ImageMagick-7.1.0-31/configure --prefix=/usr/local --with-bzlib=yes --with-fontconfig=yes --with-freetype=yes --with-gslib=yes --with-gvc=yes --with-jpeg=yes --with-jp2=yes --with-png=yes --with-tiff=yes --with-xml=yes --with-gs-font-dir=yes && \
>     make -j && make install && ldconfig /usr/local/lib/
> 
> WORKDIR /tmp
> 
> 
> RUN pip install --upgrade pip
> 
> WORKDIR /app
> 
> ADD ./requirements.txt .
> RUN pip install -r requirements.txt
> 
> ADD ./Backend ./backend
> ADD ./Frontend ./frontend
> ADD ./fonts ./fonts
> ```
> 
> @Bartixxx32 

Ty, ill try it later, im asking for dockerfile due to im using arm64 and need rebuild everytime

**Comment by Aikpo** [comment]
hey do i need to change my python version to fix the sound ?

**Comment by esteinborn** [comment]
> Can someone try this
> 
> Docker image = `istorry/moneyprinter:audiofix`

I still do not have audio on the output.mp4 file

BTW thanks for all the work getting this set up!

**Comment by FujiwaraChoki** [comment]
> > Can someone try this
> > Docker image = `istorry/moneyprinter:audiofix`
> 
> I still do not have audio on the output.mp4 file
> 
> BTW thanks for all the work getting this set up!

Open using VLC. Also, please use Python 3.11! (Will add to README)

**Comment by GregHilston** [comment]
@iStorry and others, I know this issue is closed, but is anyone else still not having magik issues?

```
[+] Building 143.8s (26/26) FINISHED                                                                                                          docker:default
 => [money-printer-frontend internal] load build definition from Dockerfile                                                                             0.0s
 => => transferring dockerfile: 1.16kB                                                                                                                  0.0s
 => [money-printer-backend internal] load metadata for docker.io/library/ubuntu:22.04                                                                   0.0s
 => [money-printer-frontend internal] load .dockerignore                                                                                                0.0s
 => => transferring context: 2B                                                                                                                         0.0s
 => [money-printer-frontend internal] load build context                                                                                                0.0s
 => => transferring context: 656B                                                                                                                       0.0s
 => [money-printer-backend  1/12] FROM docker.io/library/ubuntu:22.04                                                                                   0.0s
 => CACHED [money-printer-backend  2/12] RUN apt-get update && apt-get install --no-install-recommends -y python3.11     python3-dev python3-pip buil  27.2s
 => CACHED [money-printer-backend  3/12] RUN apt-get update && apt-get install -y wget &&     apt-get install -y build-essential curl libpng-dev &&    11.5s  => CACHED [money-printer-backend  4/12] RUN sh ./ImageMagick-7.1.0-31/configure --prefix=/usr/local --with-bzlib=yes --with-fontconfig=yes --with-fr  69.7s  => CACHED [money-printer-backend  5/12] WORKDIR /tmp                                                                                                   0.0s  => CACHED [money-printer-backend  6/12] RUN pip3 install --upgrade pip                                                                                 3.3s  => CACHED [money-printer-backend  7/12] WORKDIR /app                                                                                                   0.0s  => [money-printer-frontend  8/12] ADD ./MoneyPrinter/requirements.txt .                                                                                0.0s  => [money-printer-frontend  9/12] RUN pip3 install -r requirements.txt                                                                                28.3s  => [money-printer-frontend 10/12] ADD ./MoneyPrinter/Backend ./backend                                                                                 0.0s  => [money-printer-frontend 11/12] ADD ./MoneyPrinter/Frontend ./frontend                                                                               0.0s  => [money-printer-frontend 12/12] ADD ./MoneyPrinter/fonts ./fonts                                                                                     0.0s  => [money-printer-frontend] exporting to image                                                                                                         3.5s  => => exporting layers                                                                                                                                 3.5s  => => writing image sha256:7d380c69477e902e2e36fcf5e69b13330424de1f4f0a7f91d1190eee7570c4c2                                                            0.0s  => => naming to docker.io/library/home-lab-money-printer-frontend                                                                                      0.0s
 => [money-printer-backend internal] load build definition from Dockerfile                                                                              0.0s
 => => transferring dockerfile: 1.16kB                                                                                                                  0.0s
 => [money-printer-backend internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                         0.0s
 => [money-printer-backend internal] load build context                                                                                                 0.0s
 => => transferring context: 656B                                                                                                                       0.0s
 => CACHED [money-printer-backend  8/12] ADD ./MoneyPrinter/requirements.txt .                                                                          0.0s
 => CACHED [money-printer-backend  9/12] RUN pip3 install -r requirements.txt                                                                           0.0s
 => CACHED [money-printer-backend 10/12] ADD ./MoneyPrinter/Backend ./backend                                                                           0.0s
 => CACHED [money-printer-backend 11/12] ADD ./MoneyPrinter/Frontend ./frontend                                                                         0.0s
 => CACHED [money-printer-backend 12/12] ADD ./MoneyPrinter/fonts ./fonts                                                                               0.0s
 => [money-printer-backend] exporting to image                                                                                                          0.0s
 => => exporting layers                                                                                                                                 0.0s
 => => writing image sha256:4af7fc283b8b706a245e781fd0d9e59cad8b12d8ba4b6e3a6b8658289a6af9ec                                                            0.0s
 => => naming to docker.io/library/home-lab-money-printer-backend                                                                                       0.0s
[+] Running 2/1
 ✔ Container money-printer-frontend  Recreated                                                                                                         10.5s  ✔ Container money-printer-backend   Recreated                                                                                                          0.0s Attaching to money-printer-backend
money-printer-backend  | Traceback (most recent call last):
money-printer-backend  |   File "/app/backend/main.py", line 4, in <module>
money-printer-backend  |     from video import *
money-printer-backend  |   File "/app/backend/video.py", line 9, in <module>
money-printer-backend  |     from moviepy.editor import *
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/editor.py", line 36, in <module>
money-printer-backend  |     from .video.io.VideoFileClip import VideoFileClip
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
money-printer-backend  |     from moviepy.audio.io.AudioFileClip import AudioFileClip
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
money-printer-backend  |     from moviepy.audio.AudioClip import AudioClip
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/AudioClip.py", line 7, in <module>
money-printer-backend  |     from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
money-printer-backend  |     from moviepy.config import get_setting
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/config.py", line 67, in <module>
money-printer-backend  |     raise IOError(
money-printer-backend  | OSError: ImageMagick binary cannot be found at "/usr/bin/convert"
money-printer-backend exited with code 0
```

From this dockerfile:

```dockerfile
# Based on https://github.com/FujiwaraChoki/MoneyPrinter/issues/97
FROM ubuntu:22.04

RUN apt-get update && apt-get install --no-install-recommends -y python3.11 \
    python3-dev python3-pip build-essential \
    autoconf pkg-config wget ghostscript

RUN apt-get update && apt-get install -y wget && \
    apt-get install -y build-essential curl libpng-dev && \
    wget https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.0-31.tar.gz && \
    tar xzf 7.1.0-31.tar.gz && \
    rm 7.1.0-31.tar.gz && \
    apt-get clean && \
    apt-get autoremove

RUN sh ./ImageMagick-7.1.0-31/configure --prefix=/usr/local --with-bzlib=yes --with-fontconfig=yes --with-freetype=yes --with-gslib=yes --with-gvc=yes --with-jpeg=yes --with-jp2=yes --with-png=yes --with-tiff=yes --with-xml=yes --with-gs-font-dir=yes && \
    make -j && make install && ldconfig /usr/local/lib/

WORKDIR /tmp

RUN pip3 install --upgrade pip

WORKDIR /app

ADD ./MoneyPrinter/requirements.txt .
RUN pip3 install -r requirements.txt

ADD ./MoneyPrinter/Backend ./backend
ADD ./MoneyPrinter/Frontend ./frontend
ADD ./MoneyPrinter/fonts ./fonts
```

and this docker compose service:

```
  # Based on https://github.com/FujiwaraChoki/MoneyPrinter/issues/97
  money-printer-backend:
    build:
      context: ./money-printer
      dockerfile: Dockerfile
    container_name: "money-printer-backend"
    ports:
      - "8080:8080"
    command: ["python3", "backend/main.py"]
    environment:
      - ASSEMBLY_AI_API_KEY=${SECRET_ASSEMBLY_AI_API_KEY}
      # - TIKTOK_SESSION_ID=
      - IMAGEMAGICK_BINARY="/usr/bin/convert" # path referring to inside container
      - PEXELS_API_KEY=${SECRET_PEXELS_API_KEY}
    volumes:
      - ${SERVER_DATA_SHARE_MOUNT_POINT}/money-printer:/temp
    depends_on:
      - money-printer-frontend
    restart: unless-stopped

```

**Comment by iStorry** [comment]
@GregHilston Update your imagemagick path to this. Seems like you're still using the old path

｀IMAGEMAGICK_BINARY=/usr/local/bin/magick｀

**Comment by GregHilston** [comment]
@iStorry I have to do a deep dive and understand why even making that change is still causing an issue:

```
money-printer-backend  | Traceback (most recent call last):
money-printer-backend  |   File "/app/backend/main.py", line 4, in <module>
money-printer-backend  |     from video import *
money-printer-backend  |   File "/app/backend/video.py", line 9, in <module>
money-printer-backend  |     from moviepy.editor import *
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/editor.py", line 36, in <module>
money-printer-backend  |     from .video.io.VideoFileClip import VideoFileClip
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
money-printer-backend  |     from moviepy.audio.io.AudioFileClip import AudioFileClip
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
money-printer-backend  |     from moviepy.audio.AudioClip import AudioClip
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/AudioClip.py", line 7, in <module>
money-printer-backend  |     from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
money-printer-backend  |     from moviepy.config import get_setting
money-printer-backend  |   File "/usr/local/lib/python3.10/dist-packages/moviepy/config.py", line 67, in <module>
money-printer-backend  |     raise IOError(
money-printer-backend  | OSError: ImageMagick binary cannot be found at "/usr/local/bin/magick"
money-printer-backend exited with code 0
```

Do you have a forked branch, with all your files in one spot, which are working that I can reference? If not, no worries, and I'll figure it

**Comment by ceramicwhite** [comment]
Give this a shot, trimmed the fat:

```
ARG GIT_TAG=main
ARG PYTHON_VERSION=3.10
ARG IMAGEMAGICK_VERSION=7.1.1-27

########################################
FROM python:${PYTHON_VERSION}-slim as app

ARG GIT_TAG \
    IMAGEMAGICK_VERSION

ENV PIP_NO_CACHE_DIR=yes \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    DEBIAN_FRONTEND=noninteractive \
    IMAGEMAGICK_BINARY=/usr/local/bin/magick \
    PORT=${PORT:-3000} \
    LD_LIBRARY_PATH=/usr/local/lib \
    HOME=/app

ADD --keep-git-dir=false https://github.com/FujiwaraChoki/MoneyPrinter.git#${GIT_TAG} /app

WORKDIR /build

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        build-essential \
        autoconf \
        pkg-config \
        wget curl \
        procps \
        ghostscript \
        libpng-dev \
        libfreetype6-dev \
        libgomp1 \
        inotify-tools \
        ca-certificates && \
    update-ca-certificates && \
    wget https://github.com/ImageMagick/ImageMagick/archive/refs/tags/${IMAGEMAGICK_VERSION}.tar.gz && \
    tar xzf ${IMAGEMAGICK_VERSION}.tar.gz && \
    rm ${IMAGEMAGICK_VERSION}.tar.gz && \
    sh ./ImageMagick-${IMAGEMAGICK_VERSION}/configure \
        --prefix=/usr/local \
        --with-bzlib=yes --with-fontconfig=yes \
        --with-freetype=yes --with-gslib=yes \
        --with-gvc=yes --with-jpeg=yes \
        --with-jp2=yes --with-png=yes \
        --with-tiff=yes --with-xml=yes \
        --with-gs-font-dir=yes && \
    make -j$(nproc) && \
    make install && \
    ldconfig /usr/local/lib && \
    apt-get remove -y --purge \
        build-essential \
        autoconf \
        pkg-config && \
    rm -rf /build && \
    cd /app && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    mkdir -p /app/logs /app/subtitles /app/temp /app/videos && \
    printf \
'#!/bin/bash\n\
mkdir -p /app/videos\n\
(tail -n0 -F /app/logs/backend.logs & ) | grep --line-buffered "Moviepy - video ready ../temp/output.mp4" | while read line\n\
do\n\
    TIMESTAMP=$(date +%%Y%%m%%d%%H%%M)\n\
    if [ -f "/app/temp/output.mp4" ]; then\n\
        mkdir -p /app/videos/$TIMESTAMP\n\
        mv /app/temp/output.mp4 /app/videos/$TIMESTAMP/output.mp4\n\
        mv /app/subtitles/*.srt /app/videos/$TIMESTAMP/subtitles.srt\n\
        cp /app/logs/backend.logs /app/videos/$TIMESTAMP/backend.logs\n\
        echo "" > /app/logs/backend.logs\n\
        echo "Video generated: /app/videos/$TIMESTAMP/output.mp4"\n\
    fi\n\
done &\n\
cd /app/Backend\n\
nohup python main.py 2>&1 | tee /app/logs/backend.logs &\n\
sleep 3\n\
cd ../Frontend\n\
python -m http.server "$PORT" 2>&1 | tee /app/logs/frontend.logs' > ./run.sh && \
    chmod +x ./run.sh && \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* /build && \
    adduser --disabled-password --gecos '' --uid 1000 --home /app appuser && \
    chown -R 1000:1000 /app
    
USER 1000

WORKDIR /app

EXPOSE $PORT 8080

ENTRYPOINT [ "./run.sh" ]
```

```
services:
  app:
    image: ceramicwhite/moneyprinter:latest
    container_name: moneyprinter
    init: true
    restart: on-failure
    # env_file:
    #    - .env
    environment:
      - TIKTOK_SESSION_ID=
      - PEXELS_API_KEY=
      - OPENAI_API_KEY=
    #  - ASSEMBLY_AI_API_KEY= # Optional
    #  - PORT=3000 #WebUI
    volumes:
      - ./data/videos:/app/videos
      - ./data/logs:/app/logs
      #- ./client_secrets.json:/app/Backend/client_secret.json
    ports:
      - "3000:3000"
      - "8080:8080"
```

**Comment by GregHilston** [comment]
I've still been unable to shake the `OSError: ImageMagick binary cannot be found at "/usr/local/bin/magick"` error with even the main branch's latest `Dockerfile` or `docker-compose.yaml` file.

@ceramicwhite I admitedly have not tried your `Dockerfile` yet, as it is vastly different then the repository's file...
