### ISSUE TITLE
[BUG] ai.fakeopen.com

### ISSUE THREAD

**Issue by Crostrix** [FujiwaraChoki/MoneyPrinter#98]
The site no longer exists!

**To Reproduce**
1. Go to 'Money Printer'
2. Click on 'Generate'
3. Scroll down to 'The Terminal'

**Expected behavior**
Make a video

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - Browser [e.g. chrome, edge]
 - Python Version [e.g. 3.9]

**Additional context**

**Comment by 1NoobDev** [comment]
To be clear:

ai.fakeopen.com redirects to a Chinese site:  https://linux.do/t/topic/1051

**Comment by FujiwaraChoki** [comment]
Not an issue with MoneyPrinter.
