### ISSUE TITLE
[BUG]  The program doesnt run at all

### ISSUE THREAD

**Issue by AryanilPanja** [FujiwaraChoki/MoneyPrinter#99]
The Bug:
on running the program we would be finally be faced with a statement : [-] Error: float division by zero

1. Go to  Frontend and run as per the given instruction in read me (python -m http.server 3000).
2. Go to Backend and run python3 main.py
3. Go to http://0.0.0.0:3000/ in browser.
4. Put a topic and press Generate.
5.I n the terminal running backend by the messages it produces it seems like the videos aren't getting loaded with code: Unauthorized and status : 401.
6. Let the program complete and you will be greeted with - Error: float division by zero
7. See error

Expected behavior
I expected it go generate and keep the videos in temp folder.

Desktop :
 - OS: Linux
 - Browser: Firefox
 - Python Version : 3.10.12

**Comment by FujiwaraChoki** [comment]
Fill in the `.env` variables.

**Comment by 1NoobDev** [comment]
since you get: Unauthorized and status : 401. The program is running and trying to make a connection to one of the API's.. Did you entered ALL API keys? Also, the Error: float division by zero happens to me sometimes, but when I re-run the generator it does work.. It could also be related to the 401 you get, since you will get 0 somewhere if no authorization.. 

If I have time, will try to improve on error handling and verification processes in the app :)

**Comment by AryanilPanja** [comment]
> since you get: Unauthorized and status : 401. The program is running and trying to make a connection to one of the API's.. Did you entered ALL API keys? Also, the Error: float division by zero happens to me sometimes, but when I re-run the generator it does work.. It could also be related to the 401 you get, since you will get 0 somewhere if no authorization..
> 
> If I have time, will try to improve on error handling and verification processes in the app :)

Sorry if i come out as naive as i am new to open source.
But in the README file nor in the installation process there was no mentioning of entering API keys somewhere , so where should they be added? Note: I am not choosing the option of direct upload to youtube because there API keys usage was mentioned.
And for me re-running multiple times still give out the same error .
Thank you
![ss](https://github.com/FujiwaraChoki/MoneyPrinter/assets/149546454/065ef1f4-7249-489a-a075-78aa1fa7a38e)
ps: this is how the error shows up ,later the error of float division by zero and then stop.

**Comment by AryanilPanja** [comment]
> Fill in the `.env` variables.

do you mean the copy step? i remember doing that...

**Comment by AryanilPanja** [comment]
and where do we put the API keys that are mentioned in ENV.md?

**Comment by 1NoobDev** [comment]
Welcome to open source 🔥

Usage 🛠️
Copy the .env.example file to .env and fill in the required values.

Based on the image, you need to add the API key from pexels to the .env file. That's all and it'll work ☺️

**Comment by AryanilPanja** [comment]
Thanks a lot!!
